newrelic/open-install-library

.github/workflows/validation.yaml
docs/README.md
docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
examples/sample-linux-infrastructure.yaml
recipes/newrelic/infra-agent/amazonlinux2.yml
recipes/newrelic/infra-agent/centos_rhel.yml
recipes/newrelic/infra-agent/debian.yml
recipes/newrelic/infra-agent/suse.yml
recipes/newrelic/infra-agent/ubuntu.yml
recipes/newrelic/nginx/debian.yml
recipes/newrelic/nginx/rhel.yml
recipes/newrelic/nginx/suse.yml
recipes/newrelic/node-agent/node.yml
test/deploy/assertions/recipe-is-valid/roles/onafterstart/tasks/nrql_has_data.yml
validator/schema-v1.json

- License key renamed
- validationNrql updated to use Go templating

chore: updates to match latest CLI spec

---

recipes/newrelic/cassandra/debian.yml
recipes/newrelic/cassandra/rhel.yml
recipes/newrelic/flex/flex.yml
recipes/newrelic/infra-agent/amazonlinux2.yml
recipes/newrelic/infra-agent/centos_rhel.yml
recipes/newrelic/infra-agent/debian.yml
recipes/newrelic/infra-agent/suse.yml
recipes/newrelic/infra-agent/ubuntu.yml
recipes/newrelic/infra-agent/windows.yml
recipes/newrelic/logs/logs.yml
recipes/newrelic/mysql/debian.yml
recipes/newrelic/mysql/rhel.yml
recipes/newrelic/mysql/suse.yml
recipes/newrelic/nginx/debian.yml
recipes/newrelic/nginx/rhel.yml
recipes/newrelic/nginx/suse.yml
recipes/newrelic/node-agent/node.yml
recipes/newrelic/sql/ms-sql.yml

The UI needs a `name` and a `displayName`, we need to update and ensure we make changes with corresponding work in the service and CLI.

feat: step 1, add displayName

---

recipes/newrelic/redis/rhel.yml
test/definitions/ohi/linux/redis-rhel.json
test/deploy/linux/redis/install/rhel/roles/configure/tasks/main.yml
test/deploy/linux/redis/install/rhel/roles/configure/templates/epel.repo
test/deploy/linux/redis/install/rhel/roles/configure/templates/redis.conf

feat(redis-rhel): create default configuration for redis recipe

---

recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
recipes/newrelic/infrastructure/ohi/elasticsearch/rhel.yml
recipes/newrelic/infrastructure/ohi/elasticsearch/suse.yml

The if clause in elastic search had an error. This PR aims to resolve this issue.

refactor(elasticSearch): fix if clause

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/suse.yml
validator/schema-v1.json

* Update spec and schema validation to use `preInstall:info`
* Update MySQL recipes

feat(mysql): preInstall info

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

This PR attempts to fix an issue found by a customer with setting up the MSSQL OHI on Windows.

Add quotes around the hostname,port in the assert pre req step

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
validator/schema-v1.json

update recipe schema with successLink field

---

recipes/newrelic/apm/dotNet/windows/net-install.yml

This PR updates the .NET/ISS install recipe to enable DT be default.

Updates net installation recipe to enable DT by default

---

recipes/newrelic/apm/dotNet/windows/net-install.yml
test/definitions/apm/.net/windows/windows2019-iis.json

This PR updates the .NET/IIS recipe to include the succesLinkConfig for display the NR1 link with the language filter.

Adds successLinkConfig to the .NET/IIS recipe

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
recipes/newrelic/apm/dotNet/windows/net-install.yml
recipes/newrelic/apm/java/debian.yml
recipes/newrelic/apm/java/rhel.yml
recipes/newrelic/apm/java/windows.yml
validator/schema-v1.json

This PR update the type from explorer to EXPLORER to match expectation from GraphQL.

Update case of type for successLinkConfig

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
validator/schema-v1.json

related: https://newrelic.atlassian.net/browse/VIRTUOSO-684

feat: add support for dependencies

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
validator/schema-v1.json

Related: https://newrelic.atlassian.net/browse/VIRTUOSO-649

feat: add support for quickstarts

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
validator/schema-v1.json

Related: https://newrelic.atlassian.net/browse/VIRTUOSO-616

feat: add support for stability

---

recipes/newrelic/infrastructure/logs/debian-logs.yml
recipes/newrelic/infrastructure/logs/logs.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-785

Changing default verbosity level for logging recipes to 0

---

recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/suse.yml
test/deploy/linux/mysql/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/mysql/install/rhel/roles/configure/tasks/main.yml
test/deploy/linux/mysql/install/suse/roles/configure/tasks/main.yml

Changes to The Mysql recipe:
* Allow the user retry inputting data
* Added connectivity test to mysql instance
* Improved user and permissions testing
* Decoupled infra agent presence testing from mysql tests to fail before user input

Mysql improvements

---

recipes/newrelic/infrastructure/ohi/cassandra/debian.yml
recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/suse.yml
recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml
recipes/newrelic/infrastructure/ohi/postgres/debian.yml
recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
recipes/newrelic/infrastructure/ohi/redis/debian.yml
recipes/newrelic/infrastructure/ohi/redis/rhel.yml

chore(ohi): add explore page filters to redirect URLs for specific OHIs

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-951

Ensure pre-req for ms-sql is region agnostic.

---

recipes/newrelic/infrastructure/ohi/postgres/debian.yml
recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
test/deploy/linux/postgres/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/postgres/install/rhel/roles/configure/tasks/main.yml

Changes to Postgres recipe:
* Allow the user retry inputting data
* Added connectivity test to postgres instance
* Improved user and permissions testing
* SSL inputs will only be requested if USE_SSL is true
* Decoupled infra agent presence testing from mysql tests to fail before user input

Postgres improvements

---

recipes/newrelic/infrastructure/ohi/redis/debian.yml
recipes/newrelic/infrastructure/ohi/redis/rhel.yml
test/deploy/linux/redis/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/redis/install/rhel/roles/configure/tasks/main.yml

Changes to Redis recipe:
* Allow the user retry inputting data
* Added connectivity test to Redis instance
* Password requested only if Redis authentication is set
* Decoupled infra agent presence testing from apache tests to fail before user input

Redis recipe improvements

---

recipes/newrelic/infrastructure/ohi/apache/debian.yml
recipes/newrelic/infrastructure/ohi/apache/rhel.yml

Changes to Apache recipe:
* Allow the user retry inputting data
* Added connectivity test to Apache instance
* Decoupled infra agent presence testing from apache tests to fail before user input

Apache recipe improvements

---

recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/suse.yml

Implement AssumeYes in the recipe workflow

[MySQL] Implement AssumeYes

---

recipes/newrelic/apm/node/linux.yml
test/definitions/apm/node/node-linux2.json
test/deploy/linux/newrelic-cli/install-recipe/roles/onafterstart/tasks/main.yml
test/deploy/linux/newrelic-cli/install/roles/configure/tasks/main.yml

* Enabled Node recipe to be included in Guided Installations
* Updated the node recipe to align the ux with .NET including verification step

Update Node Recipe and UX

---

recipes/newrelic/apm/dotNet/windows-iis-unsupported.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-959

Detect unsupported windows version and re-route the user to manual install

---

recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml

- Autodetect status url if present and also check if NGINX PLUS or NGINX

NGINX recipe Autodetect status url and NGINX PLUS

---

recipes/newrelic/infrastructure/ohi/mysql/rhel.yml

Small fix on RHEL var assignment

Small fix on RHEL var assignment

---

recipes/newrelic/infrastructure/amazonlinux.yml
recipes/newrelic/infrastructure/amazonlinux2.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/logs/debian-logs.yml
recipes/newrelic/infrastructure/logs/docker-logs.yml
recipes/newrelic/infrastructure/logs/logs.yml
recipes/newrelic/infrastructure/ubuntu.yml
test/definitions-eu/smoke/awslinuxarm64-infra.json
test/definitions/infra-agent/debians/debian10arm64-infra.json
test/definitions/infra-agent/debians/ubuntu20arm64-infra.json
test/definitions/infra-agent/rhel/awslinuxarm64-infra.json
test/definitions/infra-agent/rhel/centos8arm64-infra.json
test/definitions/infra-agent/rhel/redhat7arm64-infra.json
test/manual/definitions/infra-agent/awslinuxarm64-infra.json
test/manual/definitions/infra-agent/centos8arm64-infra.json
test/manual/definitions/infra-agent/debian10arm64-infra.json
test/manual/definitions/infra-agent/redhat7arm64-infra.json
test/manual/definitions/infra-agent/ubuntu20arm64-infra.json

https://newrelic.atlassian.net/browse/VIRTUOSO-728

Adding support for arm64

---

recipes/newrelic/apm/php-agent/php.yml
recipes/newrelic/apm/php/debian-fpm.yml

This PR merges most of the needed changes from the other recipe. I have not tested this yet. I'm putting it up for review so others can us it as a base in order to reduce merge conflicts.

PHP: Merge changes from other recipe

---

docs/recipe-spec/recipe-spec.md
docs/recipe-spec/spec.json
validator/schema-v1.json

* add `observabilityPacks` and deprecate `quickstarts`
* minor docs update to include usage of `processMatch`

chore(docs): update schema and docs

---

recipes/newrelic/apm/java/linux.yml

This PR has improvements on the checking of the prerequisites and a small change in case catalina.sh does not have run permission.
But the bulk of it is support to some RHEL derivatives whose Tomcat packages are modified from the original version.

Improvements on Java's Tomcat recipe

---

recipes/newrelic/infrastructure/amazonlinux.yml
recipes/newrelic/infrastructure/amazonlinux2.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/suse.yml
recipes/newrelic/infrastructure/ubuntu.yml
recipes/newrelic/infrastructure/windows.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-1018

Remove infra agent cache folders

---

test/definitions/apm/php-agent/php-apache-fpm-wordpress-linux2.json
test/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
test/definitions/apm/php-agent/php-apache-wordpress-linux2.json
test/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
test/definitions/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
test/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json

Adds the auto-deploy configs for php

add php auto deploy configs

---

recipes/newrelic/infrastructure/ohi/apache/debian.yml
recipes/newrelic/infrastructure/ohi/apache/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml

- Added control of Unauthorized url and wrong host and port

Nginx & apache control authorized host and port and host errors

---

recipes/newrelic/apm/php/redhat.yml

Added latest agent download logic to redhat recipe.

PHP: Add latest agent download logic to redhat

---

recipes/newrelic/infrastructure/amazonlinux.yml
recipes/newrelic/infrastructure/amazonlinux2.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/suse.yml
recipes/newrelic/infrastructure/ubuntu.yml
recipes/newrelic/infrastructure/windows.yml

Reverts newrelic/open-install-library#440 - the problem should be fixed in the new release of the agent

Revert "fix: disable the status check in the infra recipe"

---

recipes/newrelic/infrastructure/windows.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-1108

Implement retry for windows infra check

---

recipes/newrelic/infrastructure/windows.yml

This PR will add checks if the required permissions are provided

added permissions check on windows

---

recipes/newrelic/apm/dotNet/windows-iis.yml

Resolves newrelic/newrelic-dotnet-agent#658

Fix the dotnet agent install validate step

---

recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml

Nginx: Control status url on preinstall

Nginx: Control status url on preinstall

---

recipes/newrelic/infrastructure/darwin.yml

This PR changes the location of infra-agent package

update brew tap

---

recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml
test/definitions-eu/smoke/nginx-linux2-ami.json
test/definitions/smoke/nginx-linux2-ami.json

- Remove the NGINX Plus condition since we do support it on the guided install.

Remove the NGINX Plus condition since we do support it on the guided install.

---

recipes/newrelic/infrastructure/ohi/nginx/debian.yml
recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
recipes/newrelic/infrastructure/ohi/nginx/suse.yml

Add port detection to stubs endpoint in NGINX recipe

NGINX recipe check ports

---

recipes/newrelic/apm/php/debian.yml
recipes/newrelic/apm/php/redhat.yml

https://github.com/newrelic/newrelic-php-agent/issues/215

add escaped characters in the app name

---

recipes/newrelic/infrastructure/ohi/nagios/debian.yml
recipes/newrelic/infrastructure/ohi/nagios/rhel.yml

- Correct the route where the service checks file is created in Nagios to the newer route.

nagios service checks new route

---

recipes/newrelic/apm/java/linux.yml
test/definitions/apm/java/javatomcat8-linux2.json
test/definitions/apm/java/javatomcat9-debian7.json
test/definitions/apm/php-agent/php-apache-fpm-wordpress-linux2.json
test/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
test/definitions/apm/php-agent/php-apache-wordpress-linux2.json
test/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
test/definitions/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
test/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
test/manual/definitions/apm/dotNet/linux/linux2-java.json

also updated download url to downloads.newrelic.com and uploaded artifacts for download

reinstated apm java recipe for rhel/debian x86 families only

---

recipes/newrelic/apm/node/windows.yml

To test, on a windows server, download and install nodejs https://nodejs.org/dist/v16.13.0/node-v16.13.0-x64.msi
The download demo-nodetron local https://github.com/newrelic/demo-nodetron/ and run npm install, and node .\server.js .\config\example\app_config.json
Running the newrelic-cli will now trigger the DETECTED event.

Add auto discover node windows

---

recipes/newrelic/apm/python/linux.yml
recipes/newrelic/apm/ruby/linux.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-1549

Adding detection for python and ruby

---

recipes/newrelic/apm/node/windows.yml
recipes/newrelic/infrastructure/cloud/aws-windows.yml
recipes/newrelic/infrastructure/cloud/azure-windows.yml
recipes/newrelic/infrastructure/cloud/gcp-windows.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-1578

fix: windows script need powershell command

---

recipes/newrelic/infrastructure/logs/linux-logs.yml

https://newrelic.atlassian.net/browse/VIRTUOSO-1655

Add syslog to list of detected log files

---

recipes/newrelic/apm/java/linux.yml

Prevents us from making unnecessary java LSI calls to -introspect

feat: unmatched pattern PIDs added to ignore list

---

recipes/newrelic/apm/dotNet/windows-iis.yml
recipes/newrelic/infrastructure/windows.yml
test/deploy/windows/elasticsearch/install/roles/prepare/tasks/main.yml
test/deploy/windows/iis/deploy-webapplication/roles/configure/tasks/main.yml
test/deploy/windows/iis/install/roles/prepare/tasks/main.yml
test/deploy/windows/newrelic-cli/install-recipe/roles/onafterstart/tasks/main.yml
test/deploy/windows/newrelic-cli/install/roles/onafterstart/tasks/main.yml

related PRs
https://github.com/newrelic/newrelic-cli/pull/1285
https://source.datanerd.us/open-source/nr1-install-newrelic/pull/640

chore: add tls13 to the protocol list for windows download

---

recipes/newrelic/infrastructure/kubernetes.yml

Just setting the default memory to 2Gi instead of 0.

Minor change to Pixie memory logic

---

test/deploy/linux/couchbase/install/debian/roles/configure/tasks/main.yml

Fixes timeouts in GHA non-regression suite

update couchbase ansible role for debian 

---

recipes/newrelic/infrastructure/amazonlinux.yml
recipes/newrelic/infrastructure/amazonlinux2.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/darwin.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/logs/linux-logs.yml
recipes/newrelic/infrastructure/suse.yml
recipes/newrelic/infrastructure/ubuntu.yml

Asserting for root/sudo user and removing sudo package usage from internal script commands
Reference:
https://issues.newrelic.com/browse/NR-6525

chore(infra): Allow root installs without sudo

---

recipes/newrelic/infrastructure/ohi/nginx/linux.yml

Reverts newrelic/open-install-library#686

Revert "Prompt for status stub at /status when nginx config doesn't have any"

---

test/deploy/linux/newrelic-cli/validate-recipe/roles/onafterstart/tasks/main.yml

correct copy/paste error from recent troubleshooting

fix(recipeValidate): update url variable used to post nrql validation

---

test/deploy/assertions/is-reporting/roles/configure/tasks/main.yml
test/deploy/assertions/is-reporting/roles/onafterstart/tasks/main.yml
test/deploy/assertions/recipe-is-valid/roles/configure/tasks/main.yml
test/deploy/assertions/recipe-is-valid/roles/onafterstart/tasks/main.yml
test/deploy/linux/newrelic-cli/validate-recipe/roles/configure/tasks/main.yml
test/deploy/linux/newrelic-cli/validate-recipe/roles/onafterstart/tasks/main.yml

Fixes occasional apt lock errors

chore(ansible): don't update cache when installing curl

---

recipes/newrelic/infrastructure/kubernetes.yml

Moving the if logic further up in the script.

moved if statement for k3s and k0s

---

recipes/newrelic/infrastructure/ohi/redis/debian.yml
recipes/newrelic/infrastructure/ohi/redis/rhel.yml

- fix redis typo for the password
- updated supported platforms
- add log type

chore(install): update redis password typo and supported platform

---

recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
recipes/newrelic/infrastructure/ohi/mysql/suse.yml

- also allow the user to specify a username for MySQL execution

chore(install): update mysql password with quotes

---

recipes/newrelic/infrastructure/awslinux.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/suse.yml
recipes/newrelic/infrastructure/ubuntu.yml

Not necessary functionality for guided install

Revert "feat(envars): write NRIA_PASSTHROUGH_ENVIRONMENT 

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

Remove special character '-' causing issue with sqlcmd

fix: remove special character '-' causing issue with sqlcmd

---

recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml
recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
test/definitions/ohi/linux/rabbitmq-debian.json
test/definitions/ohi/linux/rabbitmq-rhel.json
test/deploy/linux/rabbitmq/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/rabbitmq/install/rhel/roles/configure/tasks/main.yml
test/manual/definitions/ohi/linux/rabbitmq-debian.json
test/manual/definitions/ohi/linux/rabbitmq-rhel.json

Enables the RabbitMQ integration (non ssl/tls scenario).

ohi(rabbitmq): non ssl/tls scenario working

---

test/definitions/ohi/linux/rabbitmq-debian.json

ohi(rabbitmq): url typo

---

recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml
recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
test/deploy/linux/rabbitmq/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/rabbitmq/install/rhel/roles/configure/tasks/main.yml

Addressing the TLS/SSL scenario and correcting variables names in ansible tasks.

ohi(rabbitmq): ssl scenario

---

recipes/newrelic/infrastructure/logs/linux-logs.yml
test/definitions/logging/redhat8-logs.json

https://issues.newrelic.com/browse/NR-46156

fix: add log support for redhat platform

---

docs/guided-java.md

WIP adding content to be used on docs.newrelic.com for our dynamic attachement/instrumentation of java apps

chore(docs): public doc content for all things java dynamic attach

---

recipes/newrelic/infrastructure/darwin.yml

* Added support to install the infra-agent in darwin arm64
**As draft as It cannot be merged until the brew PR is merged https://github.com/Homebrew/homebrew-core/pull/110567/files**

feat(infra-agent): add support to macos in arm64

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

- This would prevent fail install removing the previous config

chore(sql): Only refresh configuration after the sql account is created

---

recipes/newrelic/infrastructure/kubernetes.yml

Add new prometheus agent and curated flags.

Add new prometheus agent and curated flags

---

recipes/newrelic/infrastructure/awslinux.yml
recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/darwin.yml
recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/suse.yml
recipes/newrelic/infrastructure/ubuntu.yml

Swallowing any errors when trying to remove during cleanup

chore(delete): swallow errors on permission denied during recipe cleanup

---

recipes/newrelic/infrastructure/kubernetes.yml

Need to capture if the user chose to uninstall or skip uninstalling nri-bundle (this question is only prompted if the bundle was already installed). 
Also capturing the helm upgrade command before it's executed to help us troubleshoot errors with this command if there's an error with helm upgrade args.

feat(k8s): capture additional metadata with user actions

---

recipes/newrelic/infrastructure/kubernetes.yml

Catch command errors for helm add, helm update and kubectl apply

fix: catch command errors

---

recipes/newrelic/infrastructure/centos_rhel.yml
recipes/newrelic/infrastructure/windows.yml
test/deploy/linux/newrelic-cli/install-recipe/roles/onafterstart/tasks/main.yml
test/deploy/linux/newrelic-cli/install/roles/onafterstart/tasks/main.yml
test/deploy/windows/newrelic-cli/install-recipe/roles/onafterstart/tasks/main.yml
test/deploy/windows/newrelic-cli/install/roles/onafterstart/tasks/main.yml

https://issues.newrelic.com/browse/NR-83641

fix: set env var on host

---

recipes/newrelic/apm/dotNet/windows-iis.yml
recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml
recipes/newrelic/infrastructure/windows.yml

Adds optional proxy configuration for agent .msi downloads

Add proxy support for Windows recipes

---

recipes/newrelic/infrastructure/kubernetes.yml

upstream version of #874 instead of fork
PR also removes a lot of trailing white space. might be better to review with this link: https://github.com/newrelic/open-install-library/pull/875/files?diff=unified&w=1

[k8s] add support for NR_CLI_PROMETHEUS_AGENT_LOW_DATA_MODE

---

recipes/newrelic/infrastructure/kubernetes.yml

we want to be able to specify low data mode specifically for each charts. this PR adds the CLI flags necessary to make this happen

add support for logging low data mode

---

recipes/newrelic/infrastructure/kubernetes.yml

we want to be able to support custom app labels for prometheus. this PR adds the ability to do that when `NR_CLI_PROMETHEUS_CUSTOM_APP_LABELS` env var is set

[k8s] support prometheus custom app labels

---

recipes/newrelic/infrastructure/awslinux.yml

Corrects small infra agent's status url typo.

chore(infra): fix status url typo

---

recipes/newrelic/infrastructure/windows.yml

- Prior JSON was failing on CLI JSON validation, looks like it's validating per line. Update JSON to be a one-liner for time being.

fix: Write metadata in correct format

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml
recipes/newrelic/infrastructure/windows.yml

Enable Windows recipe to retrieve Infrastructure Agent's entity key. Allow MSSQL recipe to validate through that entity.

feat(ohi): Retrieve and validate via Windows Infra Agent's Key

---

recipes/newrelic/apm/php/debian.yml
recipes/newrelic/apm/php/redhat.yml

This reverts commit 20af5bdf8734f305d0b10c3253bb394da434aa35.

Revert "fix: php recipe display prereq output to user"

---

recipes/newrelic/infrastructure/windows.yml

As part of [NR-108089](https://issues.newrelic.com/browse/NR-108089)

fix(infra-win): error handling for start_infra

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

Fixes names of variables used to create the DB user

fix(mssql): Fix sqlcmd credential override

---

test/deploy/linux/shell/roles/configure/tasks/main.yml
test/deploy/linux/shell/roles/onafterstart/tasks/main.yml
test/deploy/linux/shell/roles/onbeforestart/tasks/main.yml
test/deploy/linux/shell/roles/onstart/tasks/main.yml
test/deploy/linux/shell/roles/prepare/tasks/main.yml
test/deploy/linux/shell/roles/upload/tasks/main.yml

Enable the prototype in https://github.com/newrelic/onboarding-e2e-tests/pull/28

feat: add shell role for installing anything

---

recipes/newrelic/infrastructure/kubernetes.yml

Update the Pixie Operator Chart Versions after[ bumping them in the nri-bundle chart](https://github.com/newrelic/helm-charts/pull/1108)
Run the following command to make sure the installation script works locally
```
xqi@TFXCKKXMP9 istio-1.17.3 % NEW_RELIC_CLI_SKIP_CORE=1 NR_CLI_CLUSTERNAME=k8scluster126 NR_CLI_NAMESPACE=newrelic NR_CLI_PRIVILEGED=true NR_CLI_LOW_DATA_MODE=true NR_CLI_KSM=true NR_CLI_KUBE_EVENTS=true NR_CLI_PROMETHEUS_AGENT=true NR_CLI_PROMETHEUS_AGENT_LOW_DATA_MODE=true NR_CLI_CURATED=false NR_CLI_NEWRELIC_PIXIE=true NR_CLI_PIXIE_API_KEY=px-api-0ef7164a-9c14-4770-b228-e3b83cec15e3 NR_CLI_PIXIE=true NR_CLI_PIXIE_DEPLOY_KEY=px-dep-a8f4ee5e-3c47-4828-9a3a-c2b6f2ecabae NEW_RELIC_API_KEY=NRAK-E5XK8L5TG5ZH5Y82OM7XXDYD874 NEW_RELIC_ACCOUNT_ID=3808497 /usr/local/bin/newrelic …
```

Update Pixie Operator Chart Versions

---

docs/mongodb.md
recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
test/deploy/linux/mongodb/install/debian/roles/configure/tasks/main.yml
test/deploy/linux/mongodb/install/rhel/roles/configure/tasks/main.yml
test/deploy/linux/mongodb/install/rhel/roles/configure/templates/mongodb-org-4.4.repo
test/deploy/linux/mongodb/install/rhel/roles/configure/templates/mongodb-org-6.0.repo

Updates the MongoDB recipe to use the new [MongoDB integration](https://docs.newrelic.com/docs/infrastructure/host-integrations/host-integrations-list/mongodb/mongodb-monitoring-integration-new/) which supports MongoDB 4.0 or higher.

New MongoDB recipe (nri-mongodb3)

---

recipes/newrelic/infrastructure/ohi/mongodb/windows.yml

Updates only `info/url` sections of the MongoDB recipe for Windows.

fix(mongodb): Update info/url for Windows

---

.github/workflows/nonregression-eu-temp.yml

Enabling a temporary GHA workflow to debug/troubleshoot failing tests.

fix(tests): Add temporary test workflow

---

.github/workflows/nonregression-eu-apm.yml
.github/workflows/nonregression-eu-reusable.yml

Try reusable workflows

---

test/definitions-eu/infra-agent/rhel/redhat8arm64-infra.json
test/definitions-eu/otel/rhel/redhat8arm64-otel.json

Updates AMI names for RHEL 8 ARM Otel/Infra tests.

fix(test): Update RHEL AMIs

---

test/definitions-eu/otel/rhel/awslinux23-otel.json
test/definitions/alerts/amazonlinux-2023-golden.json
test/definitions/infra-agent/amazonlinux2023-infra.json
test/definitions/logging/amazonlinux2023.json
test/definitions/otel/rhel/awslinux23-otel.json
test/definitions/otel/rhel/redhat8arm64-otel.json
test/manual/definitions/infra-agent/redhat8arm64-infra.json

Update several test definition files with a newer AMI name.

fix(tests): Update AMIs

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/logs/linux-logs.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Fix new config setup for super-agent release.
Logs-super-agent no longer has a dependency.

Fix new config setup

---

test/definitions-eu/apm/java/deb10-sysd-jboss.json
test/definitions-eu/infra-agent/debians/ubuntu16-infra.json
test/definitions-eu/otel/debians/ubuntu16-otel.json
test/definitions-eu/super-agent/debians/ubuntu16-super-agent.json
test/definitions/otel/debians/ubuntu16-otel.json
test/definitions/smoke/rhl2-sysd-jboss.json
test/definitions/super-agent/debians/ubuntu16-super-agent.json
test/manual/definitions/infra-agent/ubuntu16-infra.json

- Updates Ubuntu 16 AMIs
- Prevents name collision for smoke test

Fix nonregression tests

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/logs/linux-logs.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

- Add all repository to allow Fluentbit and integrations installation
- Remove dependency from logging causing it to fail
- Fix bugs on Host Monitoring

Super Agent recipe, add all repository to allow Fluentbit installation and fix bugs

---

recipes/newrelic/infrastructure/kubernetes.yml

Remove k8s 1.23 from supported versions and add k8s 1.28 support.

feat: Update supported k8s versions

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Remove deprecated values-file modification for super-agent recipe in staging

Remove deprecated values-file modification for super-agent recipe in staging

---

README.md
docs/kubernetes-eks.md
docs/kubernetes.md

Jira - https://new-relic.atlassian.net/browse/NR-200909

chore: Update minor typo errors

---

test/deploy/linux/ruby/ruby-on-rails/redhat/roles/configure/tasks/main.yml
test/manual/definitions/apm/go/go-linux2.json
test/manual/definitions/apm/ruby/rubyonrails.json

This PR will add config for Ruby on rails with a sample application
Ticket: [https://new-relic.atlassian.net/browse/NR-216878](https://new-relic.atlassian.net/browse/NR-216878)

feat: Added a config Ruby on rails

---

test/deploy/linux/python/install/rhel/roles/configure/tasks/main.yml
test/deploy/linux/python/install/rhel/roles/configure/templates/app.py
test/deploy/linux/python/install/rhel/roles/configure/templates/requirements.txt
test/manual/definitions/apm/python/python-al2.json

Testing the e2e with a sample python app

feat(python): Python sample application for e2e testing

---

test/deploy/linux/go/redhat/roles/configure/tasks/main.yml
test/deploy/linux/go/templates/server.go

Added creation of go mod and go sum to go deploy config

chore:update go deploy config with go mod and go sum

---

test/deploy/linux/go/redhat/roles/configure/tasks/main.yml
test/manual/definitions/apm/go/go-linux2.json

added go path and permissions for go folder

chore:added go path and permissions

---

test/deploy/linux/go/redhat/roles/configure/tasks/main.yml
test/manual/definitions/apm/go/go-linux2.json

added export go modules task to deploy conifg

Go modules update

---

test/definitions-eu/smoke/nginx-linux2-ami.json
test/definitions/ohi/linux/nginx-linux2-ami.json

Fixes image not found for `nginx-linux-2-ami` test (Ref: [NR-232715](https://new-relic.atlassian.net/browse/NR-232715))

chore(tests): Update nginx-linux-2 ami

---

test/deploy/linux/php/docker-php/redhat/roles/configure/tasks/main.yml
test/deploy/linux/php/docker-templates/Dockerfile
test/deploy/linux/php/docker-templates/index.php
test/manual/definitions/apm/php-agent/docker-php-linux2.json

Added deploy config for php-docker flow including test Dockerfile and Sample PHP application file

Pchinthapenta nr 191162

---

test/deploy/crowdstrike/roles/configure/tasks/main.yml
test/manual/definitions/infra-agent/ubuntu20-infra-crowdstrike.json
test/manual/definitions/infra-agent/ubuntu20-infra.json

chore: Add crowdstrike deploy tasks

---

test/deploy/linux/php/docker-php/redhat/roles/configure/tasks/main.yml

Small change to yum package update command to auto approve as part of 
JIRA: https://new-relic.atlassian.net/browse/NR-191162

chore: Modified yum package update command to auto approve

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Made this change for the cli to discover the agent every time and deal with it if its running on host

fix(super-agent): Discover agent everytime

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Change the super-agent recipe to use “integrations_only” instad of “forward_only”.

Modify super-agent's infra-agent config to use the new flag is_integrations_only.

---

recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml

Enables local validation for mongodb.

feat: Mongodb local validation

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

Enables local validation for Microsoft SQL Server.

feat: Local validation mssql

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Adapt the super-agent recipe to add the Schema when editing the Otel Collector endpoint.
It is a new requirement that was  edited for our otel collector release:
- [Optimize and align host monitoring config with newrelic-opentelemetry-examples](https://github.com/newrelic/opentelemetry-collector-releases/pull/115/files#diff-26db36ffc817266dc58ecfee77c2d48a7b42090938e644ab8bf35b4696f3e3e3R14)

Adapt Recipe/Super Agent build to Otel Collector URL + Schema

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

chore: improve SI error on creation (NR-314131)

---

recipes/newrelic/infrastructure/kubernetes.yml

Ticket: https://new-relic.atlassian.net/browse/NR-316626
1: Added PIXIE support for kops in guided install

feat(kubernetes): Add PIXIE support for kops in guided install

---

recipes/newrelic/infrastructure/kubernetes.yml
test/deploy/linux/kubernetes/minikube/roles/prepare/tasks/main.yml

Add Kube 1.31 support and drop 1.26
Update testing to use Kube v1.31.0 instead of v1.26.1 for minikube

feat(kubernetes): Add Kube 1.31 support and drop 1.26

---

recipes/newrelic/infrastructure/super-agent/debian.yml
recipes/newrelic/infrastructure/super-agent/rhel.yml
recipes/newrelic/infrastructure/super-agent/suse.yml

Related changes:
- Agent Control: https://github.com/newrelic/newrelic-super-agent/pull/943
- Helm charts: https://github.com/newrelic/helm-charts/pull/1548

feat: rename `opamp` option to `fleet_control`

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

Add fixed version for newrelic-agent-control

NR-324320-Add-fixed-version-for-agent-control

---

recipes/newrelic/infrastructure/kubernetes.yml

fix(APM): Adding eAPM config

---

recipes/newrelic/infrastructure/kubernetes.yml

fix(kubernetes): Adding eAPM config

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

bumps the AC default version to latest

deps: bump AC to 0.29.0

---

.github/workflows/scripts/deployer-platform/package.json
test/deploy/linux/python/install/rhel/roles/configure/templates/requirements.txt
validator/package-lock.json
validator/package.json

[Jira](https://new-relic.atlassian.net/browse/NR-360591)
**Dependabot Alerts issues:-**
[Issue 1](https://github.com/newrelic/open-install-library/security/dependabot/18)
[Issue 2](https://github.com/newrelic/open-install-library/security/dependabot/4)
[Issue 3](https://github.com/newrelic/open-install-library/security/dependabot/15)
[Issue 4]( https://github.com/newrelic/open-install-library/security/dependabot/14)
[Issue 5](https://github.com/newrelic/open-install-library/security/dependabot/13)
I updated the dependencies for above issues to avoid vulnerabilities.

fix(dependabot_alerts): Updated dependencies to fix dependabot alerts

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

fix: version

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

New agent control release 0.32.0

chore: Agent control release-0.32.0

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

feat: bump AC version to 0.33.0

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

chore: bump AC 0.34.0

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

bumps the AC default version to latest

chore(ac): update version for PP

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

Move the endpoint to the agent-control.conf

feat: move otel endpoint to systemd file

---

recipes/newrelic/infrastructure/debian.yml
recipes/newrelic/infrastructure/ubuntu.yml

internal branch merge for https://github.com/newrelic/open-install-library/pull/1169 PR

Nr 365936 fix guided install apt warning msg

---

.github/workflows/nonregression-eu.yml
.github/workflows/nonregression.yml
.github/workflows/scripts/depricatedOSTest.js
test/definitions-eu/infra-agent/rhel/redhat7-infra.json
test/definitions-eu/infra-agent/suse/suse153-infra.json
test/definitions-eu/otel/rhel/redhat7-otel.json
test/definitions/otel/rhel/redhat7-otel.json

excluded tests that are using deprecated OS. 
Please find the details of the excluded tests and further analysis on the deprecated os in this [doc](https://docs.google.com/document/d/1qv885CXmdi9E4F6E69Wis4EXb7BX3kRwP0z2Hew-aKw/edit?tab=t.0)
Jira ticket:  https://new-relic.atlassian.net/browse/NR-396172

fix(regression-tests): Exclude tests that use deprecated os.

---

recipes/newrelic/infrastructure/ohi/mysql/debian.yml
recipes/newrelic/infrastructure/ohi/mysql/rhel.yml

https://new-relic.atlassian.net/browse/NR-385544
https://new-relic.atlassian.net/browse/NR-401679 
test cases - https://docs.google.com/document/d/1VWA-1EIOigubdsLdflK-RrZjeqsscb97HcV-7IsMMZ8/edit?tab=t.0
https://new-relic.atlassian.net/browse/NR-401680. 
test cases - https://docs.google.com/document/d/1gKFoY4-CheZWpAfjaznfxyz6XFb1qs0y7Idr8iMVOQI/edit?tab=t.0

feat: Added minor enhancements to MySQL recipe

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

bumps ac version to latest release

feat: bump ac pinned version to 0.37.0

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

chore: bump agent control version 0.38.0

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

bum agent control version to 0.39.0

chore: bump agent control version to 0.39.0

---

recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml

- Update the automatic install recipe for Azure SQL Database
**Test Results:**
- perma link : https://staging.onenr.io/0oQDWKlg5jy

fix: Update the automatic install recipe for Azure SQL Database

---

recipes/newrelic/infrastructure/agent-control/debian.yml
recipes/newrelic/infrastructure/agent-control/rhel.yml
recipes/newrelic/infrastructure/agent-control/suse.yml

Bump agent control version to 0.41.0

chore: bump agent control version to 0.41.0

---

recipes/newrelic/infrastructure/awslinux.yml

- Fixed version specific install failure on amazon linux 2 issue.
Ticket: https://new-relic.atlassian.net/browse/NR-308200
**1: AMazon Linux 2 :**
**2: Amazon linux 2023:**

fix: Fixed Infra linux 2 ver specific install failure

---

recipes/newrelic/ebpf/centos.yml
recipes/newrelic/ebpf/ubuntu.yml

This PR updates OTLP port from `4317` to `443`

fix(ebpf): Update OTLP port to 443 

---

recipes/newrelic/infrastructure/agent-control/debian.yml

- Fix agent control gpg signature for debian.

fix: agent control gpg signature and migration rights
