newrelic/open-install-library

- recipes/newrelic/infra-agent/amazonlinux2.yml
- recipes/newrelic/infra-agent/centos_rhel.yml
- recipes/newrelic/infra-agent/debian.yml
- recipes/newrelic/infra-agent/suse.yml
- recipes/newrelic/infra-agent/ubuntu.yml
- recipes/newrelic/infra-agent/windows.yml
- recipes/newrelic/nginx/debian.yml
- recipes/newrelic/nginx/rhel.yml
- recipes/newrelic/nginx/suse.yml
This PR allows the CLI to pull the host's entity GUID from the validation queries specified in each recipe.
> chore: add facets for entityGuid to validation queries

- test/deploy/linux/newrelic-cli/install-recipe/roles/configure/tasks/main.yml
Recent changes to the CLI messaging cause a situation where the deployer tests get stuck waiting for the user to confirm y/n to install integrations (even when `-c` flag is passed). 
This change uses the `-y` flag to bypass that restriction until we get a proper fix into the CLI (the original intent of the `-c` flag is prompt wouldn't be required)
> fix: use -y to accept prompts

- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
This PR updates the MySQL OHI play in 2 ways:
* it now uses the NR_CLI_DB_PORT when checking the database connection (to support databases listening on non standard ports)
* it allows for using the current mysql user if it has  'ALL PRIVILEGES' or 'SELECT, REPLICATION' permissions
The other MySQL OHIs will need to be updated in a similar way, but I wanted to get this first pass in and make sure it was acceptable before completing the work.  Plus I do not have a way to test anything beyond the MySQL setup.
> Updating Mysql OHI integration plays

- recipes/newrelic/infrastructure/ohi/consul/debian.yml
- recipes/newrelic/infrastructure/ohi/consul/rhel.yml
- recipes/newrelic/infrastructure/ohi/haproxy/debian.yml
- recipes/newrelic/infrastructure/ohi/haproxy/rhel.yml
- recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
- recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
- recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml
- recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
- recipes/newrelic/infrastructure/ohi/varnish/debian.yml
- recipes/newrelic/infrastructure/ohi/varnish/rhel.yml
Moves existing `create_user_notification` tasks to `preInstall:info`. Still need to add preInstall info to:
* apache
* cassandra
* couchbase
* elasticsearch
* jmx
* memcached
* nginx
* redis
* mssql
Those will be addressed in future PR.
> feat: add preInstall info

- recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
- recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
During the `preInstall` step, the user needs to run `rs.initiate()` from the `mongo` shell in order to execute the rest of the commands listed. 
If `rs.initiate()` is not run, the following error occurs when trying to run the suggested commands
```
> db.createRole({ role: "listCollections", privileges: [{ resource: {db:"",collection:""}, actions: ["listCollections"] }], roles: [] })
uncaught exception: Error: not master :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
DB.prototype.createRole@src/mongo/shell/db.js:1675:15
@(shell):1:1
```
> chore(mongodb): add rs.initiate() to preInstall helper commands for mongodb

- examples/sample-linux-infrastructure.yaml
- recipes/newrelic/apm/go/linux.yml
- recipes/newrelic/apm/go/windows.yml
- recipes/newrelic/apm/java/linux.yml
- recipes/newrelic/apm/java/windows.yml
- recipes/newrelic/apm/php/linux.yml
- recipes/newrelic/apm/python/linux.yml
- recipes/newrelic/apm/python/windows.yml
- recipes/newrelic/apm/ruby/linux.yml
- recipes/newrelic/apm/ruby/windows.yml
- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/logs/logs.yml
- recipes/newrelic/infrastructure/ohi/flex/flex.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Without this change, the regex for several recipes are wrapped in slashes.  The
strings are taken directly as a regex, and don't need the slashes.  Here we
remove those slashes to avoid trying to incorrectly match the processes.
> fix(processMatch): remove // from regex

- recipes/newrelic/infrastructure/logs/debian-logs.yml
It turns out, those special logs are also needed for Debian linux, I just tested on debian 10 and I don't see a /var/log/secure and see a /var/log/auth.log as well as a /var/log/alternatives.log
> Adding debian platform for logs

- recipes/newrelic/infrastructure/ubuntu.yml
- test/definitions/infra-agent/ubuntu14-infra.json
This change works on the recent ubuntu and older versions
[ubuntu18.log](https://github.com/newrelic/open-install-library/files/6111946/ubuntu18.log)
[ubuntu14.log](https://github.com/newrelic/open-install-library/files/6111948/ubuntu14.log)
> Fix ubuntu installs for oldest version of ubuntu (<=14.04)

- recipes/newrelic/apm/dotNet/windows/net-install.yml
- recipes/newrelic/apm/java/windows.yml
- recipes/newrelic/apm/node/windows.yml
- recipes/newrelic/apm/python/windows.yml
- recipes/newrelic/apm/ruby/windows.yml
This PR removes the regex encoding from the Windows processMatch values.  This change is a temporary change to get know process to match for Windows.  At the moment when the CLI validates that a recipe with the Recipe Service (using a GraphQL call) there is a problem with encoding the slashes.  This could be an issue with the CLI or with the Recipe Service.
@michaelkro and @Julien4218 looked into this issue and figured this was the easiest/quickest way to handle this issue.  Longer term we should improve how the CLI/Recipe service handle encoding to allow for proper regex expressions in the processMatch field.
> Remove regex encoding on windows process match

- recipes/newrelic/apm/dotNet/windows/net-install.yml
Fixes the following error by checking if the `application` element has any children and skip if it doesn't:
```
Method invocation failed because [System.String] does not contain a method named 'RemoveAll'.
At line:7 char:1
+ $xdoc.configuration.application.RemoveAll();
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : MethodNotFound
```
> Wrap application.RemoveAll() in if to check for child nodes

- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/logs/debian-logs.yml
- recipes/newrelic/infrastructure/logs/docker-logs.yml
- recipes/newrelic/infrastructure/logs/logs.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
- recipes/newrelic/infrastructure/windows.yml
The underlying `sh` library used by `go-task` has some subtle differences from a native shell. Glob paths such as `/var/lib/docker/containers/*/*.log` will be expanded to the full file path such as `/var/lib/docker/containers/9483459940/9483459940.log` when trying to use with `echo`. When we try to build the discovered.yml file, we need the glob path and using a bash array avoids using `echo` and keeps the glob path intact.
This will require an update in the CLI as well since we also can't inject a multiple string into the `discoveredLogFiles` bash variable because it causes the `sh` interpreter to silently error.
Depends on: [newrelic/newrelic-cli #792](https://github.com/newrelic/newrelic-cli/pull/792)
> fix(docker-logs): build discovered logs config file using a bash array to fix "-" executable error

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Our docs say to utilize `sudo tee -a`, repeat runs of this end up creating malformed source entries
> fix(Infra Ubuntu/Debian): Remove append flag when adding to sources list to avoid malformed source(s)

- recipes/newrelic/apm/dotNet/debian-systemd.yml
Turns out that ubuntu uses "gawk" (GNU Awk) and debian uses "mawk".
`mawk` is able to do the hex->decimal conversion without any switches, but `gawk` requires the `--non-decimal-data` argument to work.  This PR updates the dotnet debian/ubuntu install recipe to detect which awk we have and adjust the logic accordingly.
> dotnet linux install: handle different types of "awk"

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
This approach allows the use of a MySQL database password containing spaces, as well as a combination of single/double quotes and other special characters.
> fix: mysql password containing spaces causes connection error

- recipes/newrelic/apm/dotNet/debian-systemd.yml
This adds more checks in the `assert_prereqs` step, to cover the tools we know we need.
I implemented these checks in a compact way, iterating over a list of strings that look like "toolname:exitcode" to handle the association between a particular tool and the expected exit code the recipe should return if that tool is not found.  (I would have used a more legit dictionary, which some versions of `bash` support, but it doesn't appear supported by the `go-task` bash interpreter.
> dotnet debian/ubuntu install: add more prereqs

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ubuntu.yml
apt-get update will return an error if any of the sources is unavailable, making the recipe fail for the infra agent. This can happen when the customer's source list contains an error. This is not something we can control and, if the agent is installed correctly, the errors will have no consequences.
> Ignore apt-get update errors

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
Noah and I discovered the following error while debugging MySQL OHI recipe
```
DEBUG executing recipe mysql-open-source-integration
read: invalid option "-d"
DEBUG Task execution returned error                 err="task: Failed to run task \"default\": task: Failed to run task \"assert_pre_req\": exit status 2"
DEBUG recipe event                                  error="encountered an error while executing mysql-open-source-integration: task: Failed to run task \"default\": task: Failed to run task \"assert_pre_req\": exit status 2" guid= recipe_name=mysql-open-source-integration status=FAILED validationDurationMilliseconds=0
```
> fix(mysql): remove -d invalid option

- recipes/newrelic/infrastructure/windows.yml
- test/definitions/infra-agent/windows/windows2016.json
- test/definitions/ohi/windows/ms-sql-server2019Standard.json
This dependency was used for logging but it's not necessary anymore.
> [Do not merge] Remove vc_redist dependency for infra on windows

- recipes/newrelic/infrastructure/amazonlinux.yml
- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Some customers receive an error because sed doesn't have permission to
modify the infra agent configuration. Add sudo in the command to fix it.
> fix: use sudo when modifying the agent config

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ubuntu.yml
I noticed that on some versions of ubuntu, gpg is not installed, which results in an error when adding the gpg key for the infra agent.
We're currently installing gpg on some versions of debian. I modified the recipe to install only when it's not already installed, which seems more robust. Let me know what you think.
> Install gnupg in ubuntu and debian

- recipes/newrelic/infrastructure/ohi/cassandra/debian.yml
- recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/rhel.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/suse.yml
- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
- recipes/newrelic/infrastructure/ohi/nginx/debian.yml
- recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
- recipes/newrelic/infrastructure/ohi/nginx/suse.yml
- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
- recipes/newrelic/infrastructure/ohi/redis/debian.yml
- recipes/newrelic/infrastructure/ohi/redis/rhel.yml
Most entities seem to have a bit of a delay before they show up in the UI, so instead of redirecting users to a blank page by filtering to a specific type of entity, it's better to have them redirected to the main explore page so they at least see their Infra host entity at the very least.
> fix(ohi): remove redirect URL filter for due to avoid redirect to blank page

- test/deploy/linux/php/apache-fpm-wordpress/debian/roles/configure/tasks/main.yml
- test/deploy/linux/php/templates/install-wordpress.sh
- test/deploy/linux/php/templates/wordpress-fpm.conf
- test/manual/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
Since I neglected to open a PR for some of my recent changes, here is a summary of the approach being used.
Both the deploy config (json file) and the ansible play (yaml file) are kept as minimal as possible.
The deploy config's job is to create the EC2 instance of the needed OS and to specify the ansible play that needs to run to install the needed services (wordpress in this case).
The ansible play's job is to install the prerequisite OS packages, copy over the template files, and run a single shell script (install-wordpress.sh). The presence or absence of OS packages or specific binaries installed by those packages are used by the install script to determine which steps to perform on the target EC2 instance.
The install script is based on our wordpress setup script in our test-apps …
> Add apache fpm deploy config

- recipes/newrelic/apm/php-agent/php.yml
Added additional tasks:
* `send_transaction`
* `create_shared`
* `delete_shared`
* `detect_services`
updated `restart_services`
Original below:
Goal is to make minimal changes to the user’s environment and to reduce the amount of questions/interactions.
The php agent needs one transaction to initialize the agent then subsequent transactions are sent to NR1.  Normally, calling `php --ini` will always use the CLI `php.ini` and the associated `newrelic.ini`.
However, by calling something like `php -c /etc/php/7.2/apache2/php.ini -c /etc/php/7.2/apache2/conf.d/newrelic.ini -n --ini`, we force the command to use ONLY the ini files used by the web server (it is forced to ignore all other INIs) and can thereby verify the data flowing pipeline without other disadvantages.
This has the advantages …
> Added send_transaction, create_shared, delete_shared, detect_services, and updated restart_services

- recipes/newrelic/apm/php-agent/php.yml
Note: This is based on Amber's PR (#359) and will need to be rebased once that is merged.
This PR adds an `assert_pre_req` step that checks the following:
* The recipe is being run via sudo.
* The target host has systemd installed.
* grep, egrep, sed, awk, and curl are installed.
The bulk of the code for this step was taken from the [.NET recipe](https://github.com/newrelic/open-install-library/blob/e7347282f607e079f528d8199b678f29dbeb4fcb/recipes/newrelic/apm/dotNet/linux-systemd.yml#L102).
> Check for PHP pre-reqs

- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
Fix for test operator errors due to random mysql reponses to curl when inputting hostname and port
```
20:8: not a valid test operator: packets
20:8: not a valid test operator: of
24:10: not a valid test operator: packets
24:10: not a valid test operator: of
```
> [Postgres] Fix test operator errors

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
Fix for test operator errors due to random mysql reponses to curl when inputting hostname and port
```
20:8: not a valid test operator: packets
20:8: not a valid test operator: of
24:10: not a valid test operator: packets
24:10: not a valid test operator: of
```
> [MySQL] Fix test operator errors

- recipes/newrelic/apm/java/linux.yml
Instead of simply matching for `catalina`, will match for the whole class that starts Tomcat.
This can prevent mismatching in case they are running another Java process which has `catalina` as part of a parameter.
> Improving Tomcat autodetection for CLI

- recipes/newrelic/infrastructure/ohi/nginx/debian.yml
- recipes/newrelic/infrastructure/ohi/nginx/rhel.yml
- recipes/newrelic/infrastructure/ohi/nginx/suse.yml
- Add check to control if user has "with-http_stub_status_module" enabled, as it's required by NGINX in order to be monitored.
- If "with-http_stub_status_module" is detected but the url failed, inform the user that also the status endpoint should be set up and point him to our documentation in order to correctly set it up.
> feat: Nginx Check if user has stub_status enabled and change error codes

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
Added exit status 130 if required env vars are not supplied when running in -y mode
> Added exit 130 - missing env vars

- recipes/newrelic/infrastructure/ohi/redis/debian.yml
- recipes/newrelic/infrastructure/ohi/redis/rhel.yml
Added exit status 130 if required env vars are not supplied when running in -y mode
> [Redis] Added exit 130 - missing env vars

- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
Added exit status 130 if required env vars are not supplied when running in -y mode
> [Postgres] Added exit 130 - missing env vars

- recipes/newrelic/apm/php/debian-fpm.yml
Adds recipe (minus validation steps/proper service restart logic) for Debian systems using PHP FPM.
There are many benefits, both in this recipe as well as future ones, to using our tarball's `newrelic-install` command to execute the initial installation.  Most helpfully, the logs of that command have shown to be invaluable in extracting valuable information about aspects of the system, such as PHP versions, and INI conf.d directories. The references to `/tmp/nrinstall*`files is that log.
While this install method is the most platform agnostic and informative, we do still want to provide the user with a method to update their agent as we release, so after this config, the APT repository is added and the agent is semi-reinstalled.
After this, there are 2 New Relic ini files in the …
> Add Debian+PHP FPM recipe

- recipes/newrelic/apm/php/debian-fpm.yml
This PR does the following:
* Prevents apt from prompting the user for license key and application name the first time the recipe is run on a system. (Fix here is to pass `DEBIAN_FRONTEND` after the call to sudo instead of before).
* Merge clean up tasks and use a wildcard to delete the temp directory in order to clean up from previous failed install attempts. (This allows us to keep around files from failed installs to aid in troubleshooting).
* Directly use recipe variables where ever possible (instead of using them to set env vars). This is less complex and has the benefit of being resilient to changes in when and where the recipe runner chooses to use a clean shell environment.
> PHP: Fix prompt on first run, improve temp file clean up

- test/deploy/linux/php/apache-fpm-wordpress/redhat/roles/configure/tasks/main.yml
- test/deploy/linux/php/apache-wordpress/redhat/roles/configure/tasks/main.yml
- test/deploy/linux/php/nginx-fpm-wordpress/redhat/roles/configure/tasks/main.yml
- test/deploy/linux/php/templates/install-wordpress.sh
- test/deploy/linux/php/templates/wordpress-httpd.conf
- test/manual/definitions/apm/php-agent/php-apache-fpm-wordpress-linux2.json
- test/manual/definitions/apm/php-agent/php-apache-wordpress-linux2.json
- test/manual/definitions/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
This PR creates PHP deploy configs for Amazon Linux 2 (a RedHat derivative). It mirrors what was done for Debian by creating a Wordpress install for Apache, Apache + FPM, and nginx + FPM.
> PHP RedHat deploy configs

- recipes/newrelic/apm/php/debian-fpm.yml
This PR reworks the colors and prompts a bit.
* Step descriptions output manually now use a cyan `===>` so we can differentiate it from output from the recipe runner.
* Step descriptions have been shortened and moved to the top of their respective task instead of sometimes being at the end.
Here's a screenshot:
> PHP: Rework colors and prompts

- recipes/newrelic/apm/dotNet/linux-systemd.yml
Adds a preinstall script to detect if a recipe should be executed.  This is based on our existing introspector task in the recipe and uses the .NET introspector to gather a list of process that are running .NET Core  or .NET 5+.  All steps that can be sent to dev/null are to prevent any extra output.
Workflow:
1. Attempts to delete the folder we use to temporarily hold the introspector - `/tmp/dotnet-introspector` (same one from the introspector task)
2. Downloads the Linux x64 introspector zip to `/tmp`
3. Creates the `/tmp/dotnet-introspector` directory for the extracted introspector
4. Extracts the intospector using zcat (no dependencies)
5. Removes the zip file from `/tmp`
6. Uses chmod to set the `/tmp/dotnet-introspector` to 777 to allow the tool to run properly
7. Runs the …
> Dotnet linux preinstall

- recipes/newrelic/apm/php/debian-fpm.yml
Expands the `assert_pre_req` and completes [166](https://github.com/newrelic/newrelic-php-agent/issues/166).
~I couldn't find a way to call a task from another task from the docs (unless it's there and I totally missed it 🙃. Otherwise, the easy thing to do is to just call the `cleanup_temp_files` task on exit.~
Confirmed that this is not possible, so I removed the cleanup. A successful run should do the necessary cleanup.
> PHP: Add assert_pre_req and cleanup on exit

- recipes/newrelic/apm/php/debian-fpm.yml
This PR reduces the number of dependencies required to run the recipe by replacing the one usage of wget with curl.
> PHP: use curl instead of wget

- recipes/newrelic/apm/php/redhat-fpm.yml
This PR adds a RedHat recipe and makes the following logic changes to both recipes:
* handle the case where a single PHP install is present (instead of separate ones for the CLI and web)
* fallback to the cli ini directory if there isn't a web specific ini directory present (this change matches what newrelic-install.sh already does)
* change the transaction sending logic to key off of whether there are web processes to restart instead of which ini directory was found
> PHP: rework transaction send, add RedHat recipe

- recipes/newrelic/apm/php/debian-fpm.yml
- recipes/newrelic/apm/php/redhat-fpm.yml
The `fpm` grep was getting triggered by the process that called a recipe containing the keyword `fpm`.
Fixed this in two ways:
1) Narrowed the keyword we search for to `php-fpm`.
2) Added `grep` clause to ignore items containing `yml` so that if a future recipe name contains the keywords we are looking for, we won't grab the line containing the call to run that recipe.
This could have been an issue with apache as well if for instance there were a recipe named `debian-apache2.yml`.
> Fix for when the recipe name contains a keyword we search for

- recipes/newrelic/apm/php/debian-fpm.yml
`curl`s the download site listing to determine the current most recent release of the PHP Agent at recipe run time.
In lieu of error checking the `curl` -> `grep` -> `head` pipeline, I opted for the simpler logic of checking the variable's emptiness.  Testing shows the same failure conditions as the following script:
```
#!/usr/bin/env bash
URL="https://download.newrelic.com/php_agent/release/"
WRONG_URL="https://download.newrelic.com/php_agent/releas/"
PATTERN='[1-9][0-9]\?\(\.[0-9]\+\)\{3\}'
WRONG_PATTERN='[1-9][A-Z]\+\(\.[0-9]\+\)\{3\}'
echo "Happy path"
if (set -o pipefail; curl -s "$URL" | grep --only-match "$PATTERN" | head -n1 ); then
echo "pass"
else
echo "fail"
fi
echo "Bad Curl"
if (set -o pipefail; curl -s "$WRONG_URL" | grep --only-match "$PATTERN" | head -n1); then
echo …
```
> Dynamically determine most recent PHP agent version

- recipes/newrelic/apm/python/linux.yml
Verified the regex is now working properly by running `newrelic install --trace`, there is no longer an error when evaluating python regex.
> Fix python regex to show recommendet nerdlet

- recipes/newrelic/apm/java/linux.yml
Keeping both the processMatch and the requireAtDiscovery because the code for the latter can take over 20 seconds.
> Java Tomcat - improving process detection

- recipes/newrelic/apm/php/debian-fpm.yml
- recipes/newrelic/apm/php/redhat-fpm.yml
1) redhat recipe: Changed debian reference to redhat.
2) redhat recipe: The RPM detection logic wasn't working for redhat.
3) both recipes: The local user on `php-apache-wordpress-linux2.json` is apache, so it's getting caught in our filter.
4) both recipes: When the user declines to accept auto service restart, ask them if they have restarted; else exit. 
5) redhat recipe: Pull over text/format/color changes from Debian to redhat.
6) both recipes: User instruction clarifications.
The redhat recipe is still not consistently running.  Putting this PR up to get the debian recipe changes incorporated.  The remaining redhat recipe changes will go in another PR after this is merged.
> PHP Virtuoso: ubuntu and redhat updates

- recipes/newrelic/apm/dotNet/windows-iis-unsupported.yml
- recipes/newrelic/apm/dotNet/windows-iis.yml
Migrates both windows-iis-unsupported.yml and windows-iis.yml to use a preInstall script.
Uses the existing assert_pre_req task script to perform the check.
Removed the assert_pre_req task entirely since we don't need to check for IIS and we want to install even if ASP.NET is not installed to support .NET Core/.NET 5+
> Migrate windows from processMatch to preinstall scripts and fixes some other issues

- test/definitions/apm/php-agent/php-apache-fpm-wordpress-linux2.json
- test/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/definitions/apm/php-agent/php-apache-wordpress-linux2.json
- test/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/definitions/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
- test/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
We recently renamed the two PHP recipes to remove the `-fpm` suffix. This PR updates the paths to the PHP recipes embedded in the automated deploy configs.
> PHP: update recipe paths in automated deploy configs

- recipes/newrelic/infrastructure/amazonlinux.yml
- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Removing /var/db/newrelic-infra also removes the installed integrations
and makes logging fails on reinstall. Only removing the data subdirectory
should be enough.
> fix/infra: don't remove the entire db directory

- recipes/newrelic/infrastructure/amazonlinux.yml
- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
- recipes/newrelic/infrastructure/windows.yml
There is a regression on release 1.19 of the agent causing the wrong
port to be used. Disabling the status check for now.
> fix: disable the status check in the infra recipe

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
Changed the name of the recipes to be 'php-agent-installer'. The dashboards are all build around tracking the recipes as whole.  We capture the platform as a field in the NRDB so we can always resolve which recipes was run by that piece of data.
> PHP Virtuoso: Adherence to naming conventions.

- recipes/newrelic/infrastructure/amazonlinux2.yml
As part of the epic to install fluent-bit package as an infrastructure-agent dependency, the Amazon Linux 2 repository location is being changed.
> feat: infrastructure agent amazon linux 2 repository new path

- recipes/newrelic/apm/php/debian.yml
This PR makes the following changes:
* Add logic to move the ini files created by the tarball installer to the location that will be used by the package installer.
* Display the detected agent version in gray instead of red. It isn't an error condition and we display the version we are using in brighter colors a little later on so it is a detail that the user can safely ignore in most cases.
* Set the color to gray when detecting services. This reduces the attention drawn to any shell output. (Aside: I'm seeing a usage message from grep displayed at this step. Not sure why, but it does not appear to be related to my changes).
**Design considerations:**
There's a question about what to do if the target ini directory doesn't exist. We could fail the install right there, but since there may …
> PHP: fix dup inis and other changes

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
1) calling Debian installer package followed by `newrelic-install` is the more common use case.
2) Call `newrelic-install` with the `NR_INSTALL_USE_CP_NOT_LN` [flag](https://docs.newrelic.com/docs/agents/php-agent/advanced-installation/silent-mode-install-script-advanced/); otherwise the installer was creating a symbolic link that was then copied into a directory referenced by another installer link which was causing issues like:
* seemingly permissions issues since the log files weren’t being written correctly
* the `php-cli` could never work due to the issue: `PHP Warning: PHP Startup: Unable to load dynamic library ‘newrelic.so’ `
3) While the web services correctly logged debug messages to agent/daemon logs, if they started first, cli processes wouldn’t write to the logs. Change …
> PHP Virtuoso: Permissions and Validation fixes

- test/definitions/apm/php-agent/php-apache-fpm-wordpress-linux2.json
- test/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/definitions/apm/php-agent/php-apache-wordpress-linux2.json
- test/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/definitions/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
- test/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
This PR contains:
- Replaces `local_source_path` with `"source_repository": "https://github.com/newrelic/open-install-library.git",`
- The `recipe_content_url` now references the `main` branch instead of `feat/php-agent`
> PHP: Update PHP test definitions

- recipes/newrelic/apm/dotNet/windows-iis.yml
@jaffinito this is a small PR to add the powershell check, this seems to have helped the infra success rate so far.
Also I've split the download from the install task, to get a more granular data in our reporting.
> Add powershell check and split download from install

- recipes/newrelic/apm/dotNet/windows-iis.yml
There have been error reports of IIS failing to start during the guided install process. We used to get similar reports for stopping IIS, but were able to resolve most of them by adding retry logic. This PR adds similar retry logic to the starting of IIS.
This should resolve: https://github.com/newrelic/newrelic-dotnet-agent/issues/656
Tested on Server 2019 and did not see any failures. The behavior of IIS failing to start is intermittent so is difficult to test for explicitly.
> Retry starting IIS if first attempt fails in .net windows iis recipe

- recipes/newrelic/apm/dotNet/windows-iis-unsupported.yml
- recipes/newrelic/apm/dotNet/windows-iis.yml
Resolves: https://github.com/newrelic/newrelic-dotnet-agent/issues/657
There have been customer complaints/questions about whether we support guided install on Server 2008/2008 R2. We already have checks to flag 2012/2012 R2 as unsupported, but we didn't have similar rules for 2008/2008 R2.
It would be great if there was a way to programmatically set a minimum supported version and reject everything under that, but I am unfamiliar with if that is supported in our recipe YMLs. If there is an easy way to do this then let me know.
I am spinning up some server 2008 instances to test and will only merge if everything works properly.
I also added some helpful messages when IIS is not installed.
> Disable support for Server 2008/2008 R2 in guided install

- recipes/newrelic/apm/php/redhat.yml
One line was still referencing a global default value vs the actual value we detect which then broke the tarball download logic when a new php agent was released.
> Virtuoso: PHP: redhat referencing global vs local var for tarball download

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
Fix to prevent grep being run with no args if a service was not detected.
Added feedback to console/log for user when a service was detected.
This addresses the PHP Agent issue newrelic/newrelic-php-agent#214.
> Fixes to PHP agent install recipe detect_services task

- recipes/newrelic/apm/php/debian.yml
https://github.com/newrelic/newrelic-php-agent/issues/213
Install fails if /etc/apt/sources.list.d/ does not exist. This should exist by default if the user has apt installed. So it could not exist on a debian system for 2 reasons:
1) The user removed the directory.
This is the case addressed by this PR. The user might have wished to remove 3rd party pkg repos at some point and wiped the whole directory.
2) The system doesn't have apt.
I don't know of any situations where a debian system wouldn't have apt installed. Is this a check that should be added to prereqs?
> guarantee sources.list.d exists before using it

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
This PR implements the preInstall:requireAtDiscovery method for the PHP agent recipes for RHEL and "debian-like" Linux distributions.  It adds numerous tests in the preInstall to verify the environment has a high probability of supporting the PHP agent installation.  Any test failures are documented by output which will appear in the newrelic-cli.log log file and also on the console if the '--debug' command line option is passed to the newrelic CLI.
This PR addresses the following issues:
- newrelic/newrelic-php-agent#208
- newrelic/newrelic-php-agent#212
- newrelic/newrelic-php-agent#213
- newrelic/newrelic-php-agent#222
- newrelic/newrelic-php-agent#227
> Php agent preinstall

- .gitignore
- recipes/newrelic/infrastructure/ohi/couchbase/rhel.yml
Incorrect indentation on non-SSL yaml configuration was causing couchbase-rhel to hang.
> Corrected yaml indentation on couchbase-rhel

- test/deploy/linux/php/apache-wordpress/debian/roles/configure/tasks/main.yml
The deploy definitions for debian for apache without php-fpm were installing php-fpm erronenously.
Addresses newrelic/newrelic-php-agent/#235.
> Remove php-fpm from the apache-wordpress role for debian.

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
Instead of assuming a certain directory structure to guess the service name, use systemctl to directly obtain the name.
> change detection of php service names

- recipes/newrelic/infrastructure/kubernetes.yml
Update the Kubernetes recipe to not install Pixie if the nodes have less than 8Gb of memory.
> Don't install Pixie if the nodes in the Kubernetes cluster have less than 8Gb of memory.

- recipes/newrelic/infrastructure/kubernetes.yml
Looks like the `NR_CLI_PIXIE_ADDRESS` variable is used but not assigned from the environment variable?
(Also, this is Mary Ann. 👋 )
> Add missing pixie address environment variable

- recipes/newrelic/infrastructure/kubernetes.yml
The Kubernetes validation was checking whether there was exactly 1 newrelic-infrastructure pod running. In clusters with multiple nodes, there is 1 newrelic-infrastructure pod per node. This PR fixes to check whether there are more than 0 newrelic-infrastructure pods running.
> Fix Kubernetes pod validation.

- recipes/newrelic/infrastructure/kubernetes.yml
Speed up the Kubernetes recipe by not waiting for the deletion of the privileged check.
> Speed up the Kubernetes recipe

- recipes/newrelic/infrastructure/kubernetes.yml
The PR contains 2 fixes:
1. **Fix driver matching**: the driver matching logic was wrong and worked because the driver variable contained whitespaces. The PR removes the whitespaces and does the correct matching. Tested with hyperkit driver on macos.
2. **Find minikube in default location**: due to sudo /usr/local/bin might not be in path for the sudo-ed user. The PR adds logic to find minikube in /usr/local/bin if it cannot be found using which.
> Fixes for installing Pixie on Minikube

- recipes/newrelic/infrastructure/kubernetes.yml
On macOS, the output of the `wc -l` command contains whitespace that messes up the if check afterwards. I've added a sed to remove the whitespace, which works both linux and macOS.
On my local machine, it sometimes takes more than 2 minutes for the newrelic-infrastructure pod to become running on minikube, this PR increases the timeout to 5 minutes.
> Small fixes to Kubernetes verification

- recipes/newrelic/infrastructure/kubernetes.yml
We still detect Kubernetes based on the presence of kubectl. Other pre-checks are moved to the install step in order to provide the customer with feedback on why the installation is not successful.
> Move pre-checks for Kubernetes to the install step

- recipes/newrelic/infrastructure/kubernetes.yml
Improve Kubernetes recipe:
* check standard path for kubectl
* detect OLM and adjust Pixie install to avoid conflicting OLM deployment
* suppress unwanted output when detecting the cluster type
* fix wrong logic in detecting whether namespace already exists
Tested on cluster with and without OLM installed.
> Improve Kubernetes recipe

- recipes/newrelic/infrastructure/alerts/golden.yml
[VIRTUOSO-1738] - Install Golden Signal Alert only once
- I have to duplicate the NRQL call to check for alert policy in pre-install.   I tried passing down the variable from NRQL query since it's used in installation as well, but it doesn't seem like pre-install and install share the same shell, so it's unable to.
- Not sure if there is a better way to do this.
> Golden signal install once

- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
If users have special characters in their database passwords, these may not be parsed properly in YML if the value is not surrounded by quotes.
This change adds single quotes around the YML value for the password which is written to the PostgreSQL integration file. Tested using `tee` syntax as in the recipe, with environment variables, and everything is picked up correctly from the environment when using either single or double quotes.
> Quote special chars

- recipes/newrelic/apm/dotNet/linux-systemd.yml
- recipes/newrelic/apm/dotNet/windows-iis.yml
Updates .NET Windows and Linux recipes to enabled in-agent log forwarding by default.
Windows:
Uses the newrelic.config to enable log forwarding since this is the primary way Windows users interact with agent config.
Updated configuration task and followed same pattern as other newrelic.config updates.
Linux:
Uses the environment variables to enable log forwarding since this is the primary way Linux users interact with the config.
Updated configuration task and followed same pattern as other config env vars.
Notes on release:
The .NET teams current target for the release that will support these changes is 03/29, but can wait for this to be pushed out on 03/31.
Resolves newrelic/newrelic-dotnet-agent#1020
> Enables in-agent log forwarding by default

- recipes/newrelic/infrastructure/kubernetes.yml
There are two updates included in this PR:
1) The preInstall checks for K8s were failing due to invalid logic comparing a string to an integer.  This has been fixed
2) Logic for setting Pixie Memory limits at install time were set as follows:
Cluster node < 4Gi memory: Pixie will not be installed
Cluster node > 4Gi but < 8Gi memory: `pemMemoryLimit=1Gi`
Cluster node > 8Gi: `pemMemoryLimit=2Gi`
> Update pixie memory logic and fix pre-install checks

- recipes/newrelic/infrastructure/kubernetes.yml
The addition of the `--no-headers` option to the `kubectl config get-contexts` command broke the `if` logic for the first case of the exit code `45` as the command headers were originally taken into account.
The `--no-headers` option was removed; could not see a reason for which it would be better to keep this option and instead update the `if` logic counts.
> fix(k8s): correct cluster detection

- recipes/newrelic/infrastructure/kubernetes.yml
The Kubernetes v3 integration moved from Beta to GA and the Infrastructure pod names have changed.  Currently, the K8s recipe is looking for a pod named `newrelic-infrastructure` which no longer exists.  I've removed the logic that was in place for the Beta and now the K8s recipe looks for a running `nrk8s-kubelet` pod instead.
https://docs.newrelic.com/docs/kubernetes-pixie/kubernetes-integration/get-started/changes-since-v3/
> Remove K8s v3 beta check

- recipes/newrelic/infrastructure/kubernetes.yml
Remove the explicit `kubectl apply` commands to create the CRDs, these are now part of the Helm chart.
> Remove kubectl apply for the CRDs

- recipes/newrelic/infrastructure/alerts/golden.yml
The Golden Rules Alerts recipe has a [high error occurrence](https://staging.onenr.io/0xVwgYLv8jJ) containing this message: `tonumber cannot be applied to: null`.
That recipe relies on the `jq` utility that processes JSON data received from the appropriate NerdGraph Environment. There seems to be instances where `id` is `null` (most research is needed to find/confirm this case).
The issue is easily reproduced with this piece of code below, note `id` equals `null`:
```sh
JSON_DATA='{"data":{"actor":{"account":{"alerts":{"policiesSearch":{"policies":[{"id":null,"name":"Golden Signals"}],"totalCount":1}}}}}}'
echo $JSON_DATA | newrelic utils jq '.data.actor.account.alerts.policiesSearch.policies[0] | select(.name=="Golden Signals") | .id | tonumber'
FATAL tonumber cannot be applied to: null …
```
> jq type conversion check

- recipes/newrelic/infrastructure/amazonlinux.yml
- recipes/newrelic/infrastructure/amazonlinux2.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
- recipes/newrelic/infrastructure/windows.yml
Pulling envars transformed to yaml in the cli and adding to `/etc/newrelic-infra.yml` for all linux distributions.  
- `custom_attributes` yaml key/values are replaced on every installation with valid JSON passed in `NRIA_CUSTOM_ATTRIBUTES`.  
- If `NRIA_CUSTOM_ATTRIBUTES` is invalid JSON or omitted from the installation command, any `custom_attributes` present will be removed
> feat(envars): NRIA_CUSTOM_ATTRIBUTES from cli to newrelic-infra.yml for linux/windows

- recipes/newrelic/infrastructure/kubernetes.yml
This PR introduces a new variable `NR_CLI_NEWRELIC_PIXIE_INSTALLED`. When the variable is set to true, the `px` command line is used to get the credentials of the Pixie installation. These credentials are used to configure the v2 of the Pixie integration.
The PR also checks for the OLM namespace. There are some cases where the `operators.operators.coreos.com` CRD is present, but OLM is actually not installed. In those cases the Pixie installation is not working properly.
Merge is pending the release of the v2 of the Pixie integration: https://github.com/newrelic/newrelic-pixie-integration/pull/54
> Pixie integration v2

- .github/workflows/validation.yml
In GitHub Actions (GHA), there are some failed occurrences of the `Validate Recipe (Unit Test)` workflow. The error reported is: **Error when evaluating 'strategy' for job 'test-deploy-recipe'. .github/workflows/validation.yml (Line: 178, Col: 15): Matrix must define at least one vector** (screenshot shown below), which is related to the `matrix strategy` returning empty values. We are adding another check in an attempt to avoid executing the next workflow job if the previous job outputs an empty (matrix) value.
Ref:
https://docs.github.com/en/actions/learn-github-actions/expressions#about-expressions;
https://github.com/dorny/paths-filter/issues/66
Screenshot of the validation error:
> fix(build): check empty github workflow matrix

- recipes/newrelic/infrastructure/alerts/golden.yml
Fix for this error: "execution failed for alerts-golden-signal: exit status 1: sed: -e expression #1, char 25: unterminated `s' command"
> fix(alerts): using jq at requiredAtDiscovery

- .github/workflows/validation.yml
Check if previous job matrix results is empty before processing the `Test Deploy Recipes` job.
> fix(build): empty matrix validation workflow error

- recipes/newrelic/infrastructure/awslinux.yml
Logic was changed in order to adjust the repo URL to support older Amazon Linux versions, as originally done by the Amazon recipes. It means, versions different from Amazon Linux 2 and Amazon Linux 2022, will default to the old [yum/el/6](https://download.newrelic.com/infrastructure_agent/linux/yum/el/6/) repo.
I tested installing the `infrastructure-agent` in these amazon linux versions shown below and it installed correctly:
- 2016.03
- 2017.03
- 2018.03
- 2
- 2022
- 2022 (arm)
> fix(infra): support older amazon linux versions

- test/deploy/linux/newrelic-cli/validate-recipe/roles/onafterstart/tasks/main.yml
After the curl fix (🎉), "Validate All" is now failing at "Run NRQL via nerdgraph" due to `newrelic_api_url` being undefined. Looks like we need to use `newrelic_api_url_to_use` instead.
[Link to error message](https://github.com/newrelic/open-install-library/runs/7013368436?check_suite_focus=true#step:6:628)
> Fix variable name for API URL

- recipes/newrelic/infrastructure/kubernetes.yml
This update adds logic that will detect the user's Helm client version.  If Helm 3 is found, Helm will be used to perform the install.  If Helm 2 is found (or Helm is not present at all), then the install will revert to using `kubectl` as the install client.  
In addition to detecting the Helm version, if `kubectl` is used for install and Pixie is selected for install, the guided install will now apply the Pixie CRDs prior to applying the New Relic manifest.  Previously, this did not happen and was generating errors.
> Add logic to revert to kubectl install when helm 2 is detected

- recipes/newrelic/infrastructure/kubernetes.yml
This change adds an if statement that checks for existing `nri-metadata-injection` jobs in the cluster.  If they exist, they will be deleted before proceeding with the install.  This has caused installation conflicts for a number of users and should provide a better experience.
> add nri-metadata-injection job cleanup to K8s recipe

- recipes/newrelic/infrastructure/awslinux.yml
Mismatch in infra recipe functionality, seems `NRIA_CUSTOM_ATTRIBUTES` envar functionality was inadvertently removed
> fix(custom-attributes): re-add custom attributes to amazonlinux infra

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Added functionality to all linux infrastructure recipes that consider `NRIA_PASSTHROUGH_ENVIRONMENT` variable from CLI and writing to `/etc/newrelic-infra.yml`
https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#integrations-variables
Comma-separated values will be parsed/written as an array in yaml.  If no values present, nothing will be added to `passthrough_environment:` in `/etc/newrelic-infra.yml`.  This means the last value 'wins' - omitting `NRIA_PASSTHROUGH_ENVIRONMENT` will delete any previously-set variables
> feat(envars): consider NRIA_PASSTHROUGH_ENVIRONMENT 

- test/definitions-eu/infra-agent/suse/suse125-infra.json
- test/manual/definitions/infra-agent/suse125-infra.json
The latest image for SUSE Linux Enterprise Server 12 SP5 is "EC2 Optimized" and does not have `curl` installed, which is causing a regression test to fail. This PR changes the pattern this version of SUSE to filter out this and future EC2 Optimized images. I have also added a manual infra definition for this version of SUSE.
> chore: update SUSE 12 SP5 AMI

- recipes/newrelic/apm/dotNet/linux-systemd.yml
The .Net Agent is going to release the major version of the agent. Part of the major release, we are going to rename a lot of our installer names as well as package names to remove confusion as well as better reflect what .NET frameworks are supported in our new Agent. Because of this change, we need to update our recipes to use the new package name. This PR changes using linux package name from `newrelic-netcore20-agent` to `newrelic-dotnet-agent`.
~~Note: Since the linux packages with the new name will only be available after we release the major version agent, this PR should only be merged after the .NET team releases the major version to avoid breaking. This is also why this PR is labeled as DRAFT.~~
> Changes linux package name from newrelic-netcore20-agent to newrelic-dotnet-agent

- recipes/newrelic/infrastructure/logs/windows-logs.yml
- test/definitions/logging/w19-logs.json
- test/manual/definitions/logging/w19-logs.json
Hi!
This change is related to https://github.com/newrelic/infrastructure-agent/pull/1125
Fluent-bit has a new input plugin for windows logs that come to "replace" winlog, by now we're updating the infrastructure-agent to accept this new plugin type and the next step will be to set it as the default plugin when installing logging for windows.
We thought on make this change transparent to the users by replacing winlog > winevtlog directly when generating the fluent-bit configuration, but the output generated by those plugins have different attribute names and so on, so we discard that option.
Regards!
https://docs.fluentbit.io/manual/pipeline/inputs/windows-event-log-winevtlog
https://fluentbit.io/announcements/v1.9.0/
Related to PR https://github.com/newrelic/open-install-library/pull/678 …
> feat: replace windows log to use winevtlog

- .github/workflows/validation.yml
Fixes the `raw.githubusercontent.com` branch replacement regex to match each URL in a string of multiple URLs rather than just a single URL. This was fixed in the nonregression/-eu workflows but not ported to the validation workflow. 
Before: https://regexr.com/6qjgq
After: https://regexr.com/6qjh3
> Fix raw repo regex in unit test workflow

- recipes/newrelic/infrastructure/kubernetes.yml
This PR adds metadata that helps track the `helm upgrade --install` command used for each helm-based install.  Key obfuscation is included.
> Add metadata for helm installs

- recipes/newrelic/apm/python/linux.yml
https://issues.newrelic.com/browse/NR-13775
On an Azure VM (debian 10.12), we were previously detecting python on some azure specific python programs:
```
azureuser@debian1012:~$ sudo ps aux | grep python | grep -v root | grep -v grep
azureuser@debian1012:~$ sudo ps aux | grep python| grep -v grep
root       670  0.0  1.7  26376 16888 ?        Ss   20:40   0:00 /usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown --wait-for-signal
root       713  0.0  2.6  30276 24708 ?        Ss   20:40   0:00 /usr/bin/python3 /usr/sbin/waagent -daemon
root       720  0.3  2.8 178708 26960 ?        Sl   20:40   0:02 python3 -u /usr/sbin/waagent -run-exthandlers
```
> fix: adjust python detection to exclude cloud provider python script

- recipes/newrelic/infrastructure/ohi/apache/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/redis/debian.yml
- Allow recipe install to continue when apt-get update fails
- Sometimes, the apt update fails due to the host having a bad configuration that's unrelated. We want to continue to attempt installation when that error occurs.
> chore(debian): Allow recipe installation continue 

- docs/mongodb.md
- recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
- recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
- test/definitions/ohi/linux/mongodb-debian.json
- test/definitions/ohi/linux/mongodb-rhel.json
This enables the mongodb recipe for the RHEL/CentOS distros. It was tested for the no-auth, scram auth and ssl/tls auth scenarios.
> ohi(mongo): rhel distro

- test/deploy/linux/rabbitmq/install/debian/roles/configure/tasks/main.yml
This removes the `Install rabbitmqctl` task in file `test/deploy/linux/rabbitmq/install/debian/roles/configure/tasks/main.yml` which is causing the `ohi/linux/rabbitmq-debian.json` test to [fail](https://github.com/newrelic/open-install-library/runs/8017702242?check_suite_focus=true#step:7:440) with the `no package matching 'rabbitmq-ctl' is available` message.
The previous task, `Install rabbitmq` in that same `test/deploy/linux/rabbitmq/install/debian/roles/configure/tasks/main.yml` file, installs `rabbitmq-server` and as part of it, the `rabbitmqctl` cli tool gets installed as well.
> ohi(rabbitmq): remove rabbitmqctl install task

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
As part of a new strategy to rotate packages GPG keys, the path of the current key will be changed. We still maintain the path of the previous key, but from now on, all the packages will be pointed to `infrastructure_agent/keys/` bucket path.
See https://download.newrelic.com/infrastructure_agent/keys/
Let us know if you need further information
---
Note: This is a C&P from https://github.com/newrelic/open-install-library/pull/785 . Credit to @rogercoll
> Update infra agents keys

- recipes/newrelic/apm/dotNet/linux-systemd.yml
- Updates preInstall-requireAtDiscovery to check if any of the three main .net packages are installed and if none are installed, exit out with status code 3.
- The new script will check both dpkg (Debian) and yum (RHEL-RPM) for the packages and record if the command was successful or not.
- Failed checks will report as a non-0 status code while success is 0.
- The if-then at the end of the check will examine all the status codes and if none are 0, we know that .NET was not installed.  If any are 0, we found .NET and should continue with the introspector.
- Tested locally on Ubuntu and RockyLinux (Centos)
> Adds a precheck script to .NET Linux installs to speed up detection

- test/definitions/ohi/linux/apache-rhel.json
- test/definitions/ohi/linux/cassandra-debian.json
- test/definitions/ohi/linux/consul-debian.json
- test/definitions/ohi/linux/consul-rhel.json
- test/definitions/ohi/linux/couchbase-debian.json
- test/definitions/ohi/linux/couchbase-rhel.json
- test/definitions/ohi/linux/docker-linux2.json
- test/definitions/ohi/linux/elasticsearch-debian.json
- test/definitions/ohi/linux/elasticsearch-rhel.json
- test/definitions/ohi/linux/elasticsearch-suse.json
- test/definitions/ohi/linux/haproxy-debian.json
- test/definitions/ohi/linux/haproxy-rhel.json
- test/definitions/ohi/linux/memcached-debian.json
- test/definitions/ohi/linux/memcached-rhel.json
- test/definitions/ohi/linux/mongodb-debian.json
- test/definitions/ohi/linux/mysql-debian.json
- test/definitions/ohi/linux/nagios-debian.json
- test/definitions/ohi/linux/nagios-rhel.json
- test/definitions/ohi/linux/nginx-debian.json
- test/definitions/ohi/linux/nginx-linux2-ami.json
- test/definitions/ohi/linux/nginx-linux2-svc.json
- test/definitions/ohi/linux/nginx-ubuntu.json
- test/definitions/ohi/linux/postgres-debian-targeted-failure.json
- test/definitions/ohi/linux/postgres-debian.json
- test/definitions/ohi/linux/postgres-rhel.json
- test/definitions/ohi/linux/redis-debian.json
- test/definitions/ohi/linux/redis-rhel.json
- test/definitions/ohi/linux/varnish-debian.json
- test/definitions/ohi/linux/varnish-rhel.json
Changes `validate_output` in `ohi/linux` test files to check for confirmation that specific integrations were installed
> chore: validate linux ohi installation

- recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml
1. When there are offline databases, the recipe stops and returns in error. Fix this by skipping the offline databases to create the NR user.
2. Allow disable buffer and reserve metrics through env variables
> fix(sql): Skip offline database to prevent error

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/darwin.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
- recipes/newrelic/infrastructure/windows.yml
This is to address [NR-53396](https://issues.newrelic.com/browse/NR-53396) which is about adding a second `infrastructure-agent` validation in case it is running on a different port. 
Changes tested in RHEL, Ubuntu, Debian, AWS Linux, Windows.
Testing: https://issues.newrelic.com/browse/NR-55799
> feat(infra): add process-based validation

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Adding `CAPTURE_CLI_LOGS` variable to all linux infra recipes.  Manually tested against ubuntu/centos/awslinux/suse
Testing with windows did not yield the same results, so it was excluded from this update.
> feat(log-capture): enable log capture for linux infra agent recipes

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Instead of using CAPTURE_CLI_LOGS to trigger which recipes should capture for potential log collection, use our recipe metadata functionality instead.
We're adding more metadata around our log capturing opt-in functionality, and having both of these flags within our recipe's `Metadata` collection is a cleaner implementation.
This library change should be released with the corresponding newrelic-cli change from PR: https://github.com/newrelic/newrelic-cli/pull/1386
> feat(capture-logs): removed go-task vars in favor of recipe metadata 

- recipes/newrelic/infrastructure/kubernetes.yml
Catch unsupported 1.25 k8s version and updated error messages displayed to user about unsupported k8s/kubectl versions.
> chore: catch unsupported k8s version

- recipes/newrelic/infrastructure/kubernetes.yml
Need to use greater than when checking for k8s version to future proof this check
> fix: use greater than when checking k8s version

- docs/kubernetes-eks.md
- docs/kubernetes.md
- test/deploy/linux/kubernetes/eks/roles/configure/tasks/installSockShop.yml
- test/deploy/linux/kubernetes/eks/roles/configure/tasks/main.yml
- test/deploy/linux/kubernetes/eks/roles/prepare/tasks/createCluster.yml
- test/deploy/linux/kubernetes/eks/roles/prepare/tasks/installEksctl.yml
- test/deploy/linux/kubernetes/eks/roles/prepare/tasks/installGit.yml
- test/deploy/linux/kubernetes/eks/roles/prepare/tasks/installKubectl.yml
- test/deploy/linux/kubernetes/eks/roles/prepare/tasks/main.yml
- test/deploy/linux/kubernetes/eks/roles/teardown/tasks/deleteCluster.yml
- test/deploy/linux/kubernetes/eks/roles/teardown/tasks/main.yml
- test/manual/definitions/kubernetes/eks-empty.json
- test/manual/definitions/kubernetes/minikube-empty.json
This PR is dependent on this demo-deployer PR to add the capability to associate an instance profile to an EC2 instance, so the host can have the proper permission to create an EKS cluster.
https://github.com/newrelic/demo-deployer/pull/104
JIRA https://issues.newrelic.com/browse/NR-67454
> chore: adding manual deploy config to create an empty eks cluster

- recipes/newrelic/infrastructure/kubernetes.yml
This pr fixes this error [caused by this line](https://github.com/newrelic/open-install-library/blob/main/recipes/newrelic/infrastructure/kubernetes.yml#L500):
```
execution failed for kubernetes-open-source-integration: exit status 1: open /tmp/newrelic-k8s.yml: permission denied
```
If this script is re-ran by the user, this error happens because it can't overwrite the existing file. This pr ensures that we remove the file if it exists and then write to it.
> fix: error when writing to existing file

- recipes/newrelic/infrastructure/kubernetes.yml
Capture metadata for errors when a user doesn't have permission to create namespace and pod isn't starting.
> fix: capture metadata for namespace permission error and pod not starting

- test/definitions-eu/infra-agent/suse/suse154-infra.json
- test/manual/definitions/infra-agent/suse154-infra.json
The infrastructure agent team released a new version, 1.34.0, that includes support for `SLES 15.4`. With this PR, we are adding test definitions for it.
Refs:
Jira: [NR-70284](https://issues.newrelic.com/browse/NR-70284), Infra-agent: [1.34.0](https://github.com/newrelic/infrastructure-agent/releases/tag/1.34.0)
> chore: SLES 15.4 test

- recipes/newrelic/infrastructure/alerts/golden.yml
1. Update discovery to search for the specific alert to avoid paging issues when the user has too many policies
2. Update to log error message instead of just exit code if the install fails. Examples of error when triggered failure on purpose.
> fix(alert): Log error message instead of just code

- recipes/newrelic/infrastructure/kubernetes.yml
Branched off of `cs/uninstall-option` to test failing golden signal test on PR.  
Seems there was a mismatch in tests on main and the kubernetes branch was behind.  Was able to rebase main and golden signals was no longer detected (which is correct)
Also wrapped the functionality added by @csongnr to respect `-y`/`--assumeYes` flags on guided install
> feat(k8s): add uninstall option

- recipes/newrelic/infrastructure/kubernetes.yml
Users are getting `execution failed for kubernetes-open-source-integration: exit status 1: rm: cannot remove '/tmp/newrelic-k8s.yml': Operation not permitted` error since we've added [this pr](https://github.com/newrelic/open-install-library/pull/829). Adding sudo to fix this.
> Fix: add sudo to removing newrelic k8s yaml file

- test/definitions/smoke/mysql-rhel.json
- test/deploy/linux/mysql/install/rhel/roles/configure/tasks/main.yml
One of our smoke tests `smoke/mysql-rhel.json` has been failing consistently when downloading the mysql community release rpm file, either with a read timeout or a null error `'NoneType' object is not callable`. 
Using `get_url` instead of `yum` for the download uncovered a 403 when trying to download the file. Tried again with `wget`, and the issue was resolved. 
Other changes:
- become: yes -> true (to resolve linting warnings)
- increased lock timeout for yum rpm install
> Fix smoke/mysql-rhel

- recipes/newrelic/infrastructure/kubernetes.yml
Update helm upgrade command to catch errors and return `UNSUPPORTED` on error.
> fix: update helm upgrade command to catch errors

- recipes/newrelic/infrastructure/kubernetes.yml
This PR adds support for Kubernetes v1.26. More specifically, this does the followings:
- Lifts up the integration for k8s v1.26 .
- Detects k8s version. For k8s >= v1.25, install KSM from the v2.7.0 image, otherwise install the v2.6.0 image. This is because k8s v1.26 can only work KSM image v2.7.0,  v1.23<= k8s <= v1.25 can work with either KSM image v2.6.0 or v2.7.0, k8s < v1.23 can only work with KSM image v2.6.0.
I have tested the recipe with a minikube cluster with the following test scenarios:
1. Helm is installed + minikube cluster with k8s v1.26
2. Helm is installed + minikube cluster with k8s v1.24
3. Helm is NOT installed + minikube cluster with k8s v1.26
4. Helm is NOT installed + minikube cluster with k8s v1.24
> Add support for Kubernetes v1.26

- recipes/newrelic/infrastructure/cloud/gcp-linux.yml
It was missing, which means the default of 'forever' is chosen. Most of the time it was 60 seconds. 
This is kinda a blind fix, hope we have some tests for this 😆
> fix(gcp): added timeout to 2s to GCP detection

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ubuntu.yml
Dumping SSL ciphers to assist troubleshooting of apt failures.  Example output:
```
==> Installing Infrastructure Agent
Detecting available SSL ciphers...
- SSLv3
- TLSv1
- TLSv1.2
- TLSv1.3
```
If any command within the new `log_ssl_ciphers` task fails, installation will continue and the failure output will be logged.
> chore(logging): output SSL ciphers for debian infra recipes

- recipes/newrelic/infrastructure/windows.yml
Custom attributes is a multi-line string provided by the newrelic-cli. When this variable is injected into the recipe, it causes a syntax error because the string is interpreted as a cmdlet. Instead, we should capture this variable in a multi-line string declaration, before using it.
> fix: windows custom attributes

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
Retrieves the tags and values the CLI exposes (via `{{.NEW_RELIC_CLI_TAGS}}`, including the `nr_deployed_by` (and any other tags passed by the installation) and adds them to the `newrelic.labels` configuration option in the `newrelic.ini` file of the PHP APM. This allows the display of those tags in NR1 for that APM.
Pre-requisite: https://github.com/newrelic/newrelic-cli/pull/1431
> feat(apm): php nr_deployed_by

- recipes/newrelic/apm/dotNet/linux-systemd.yml
- recipes/newrelic/apm/dotNet/windows-iis.yml
Reading `{{.NEW_RELIC_CLI_TAGS}}` to propagate tags from `newrelic install --tag` into the dotNet APM `labels`
More background here: https://docs.newrelic.com/docs/apm/agents/net-agent/configuration/net-agent-configuration/
> feat(apm): dotNet nr_deployed_by

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
Removes old `inputVars` method prompting user for application name and restart option. Adds support for an optional new `NEW_RELIC_APPLICATION_NAME` environment variable.
> feat(apm): Application Name Envar

- recipes/newrelic/infrastructure/kubernetes.yml
A customer complains that his k8s cluster version is not supported by Pixie. So we need to collect exact which k8s version he has for debugging purpose.
Due to nr cli limitation, we can only send the last echo message to backend. DEBUG_MESSAGE is used to collect all necessary debug info we need, not only for this Pixie issue, but for future issues. 
This DEBUG_MESSAGE is output as Metadata whenever the script exit
I have run the follow commands locally to test the new changes does not break the existing installation recipe
newrelic profiles add --profile jerry --apiKey -r us
newrelic profiles default --profile jerry
NEW_RELIC_CLI_SKIP_CORE=1 NR_CLI_CLUSTERNAME=k8scluster117 NR_CLI_NAMESPACE=newrelic NR_CLI_PRIVILEGED=true NR_CLI_LOW_DATA_MODE=true NR_CLI_KSM=true NR_CLI_KUBE_EVENTS=true …
> Add pixie debug info

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
- test/definitions/apm/php-apache-fpm-wordpress-ubuntu18.json
- test/definitions/apm/php-nginx-fpm-wordpress-linux2.json
Moved our /tmp/newrelic-php-agent directory removal/creation to assert_pre_req in order to:
1 - check permissions for rm and mkdir on /tmp
2- return 131 (UNSUPPORTED) if permissions aren't high enough to manipulate said tmp location
> fix(php): rolled tmp file creation into assert_pre_req task

- recipes/newrelic/infrastructure/kubernetes.yml
In installation recipe, when customer does not have repo newrelic installed, the script will exit due to a bug introduced in https://github.com/newrelic/open-install-library/pull/879
The error message is like `helm (version v3.11.2+g912ebc1) repo add failed due to: "newrelic" has been added to your repositories`
which should not lead to exist.
modify the code to exit only when the helm repo add command results in non zero code
I test the modified script with the following commands on K8s 1.17 and 1.26 with and without nri-bundle preinstalled.
All the testing installation succeeded
```
xqi@TFXCKKXMP9 newrelic-cli_0.65.1_Darwin_arm64 % NEW_RELIC_CLI_SKIP_CORE=1 NR_CLI_CLUSTERNAME=k8scluster117 NR_CLI_NAMESPACE=newrelic NR_CLI_PRIVILEGED=true NR_CLI_LOW_DATA_MODE=true NR_CLI_KSM=true …
```
> Fix helm repo add error msg

- recipes/newrelic/infrastructure/kubernetes.yml
- As new nri-bundles are released, we need to know which bundle version causes which issues. 
- When we see the error message like `execution failed for kubernetes-open-source-integration: exit status 33: {"Metadata":{"InstallationError":"nrk8s-kubelet pod is not starting", "K8sClientVersion":"1.26", "K8sServerVersion":"1.26"}}`, we need to know the exact pod status and how many restarts it has been went through.
In this PR, I add the code to collect the nri-bundle version, failing pod status and restarts as part of the debugging info.
Any suggestion for other debug info to be collected are welcome
I have run the follow commands locally to test the new changes does not break the existing installation recipe
NEW_RELIC_CLI_SKIP_CORE=1 NR_CLI_CLUSTERNAME=k8scluster117 …
> Collect Nri Bundle Version And Failed Pod Info

- recipes/newrelic/infrastructure/kubernetes.yml
In installation recipe, only the last echo message is sent to backend.
This [line of code](https://github.com/newrelic/open-install-library/blob/63ff51e93a8ffec8f68577b14e3fa753a2dcc8b8/recipes/newrelic/infrastructure/kubernetes.yml#L555) actually rewrites the error message so we do not get what exact error message is.
modify this part of code to send the actually error message together with the helm version to backend
I test the modified script with the following commands on K8s 1.17 and 1.26 with and without nri-bundle preinstalled.
All the testing installation succeeded
```
xqi@TFXCKKXMP9 newrelic-cli_0.65.1_Darwin_arm64 % NEW_RELIC_CLI_SKIP_CORE=1 NR_CLI_CLUSTERNAME=k8scluster117 NR_CLI_NAMESPACE=newrelic NR_CLI_PRIVILEGED=true NR_CLI_LOW_DATA_MODE=true NR_CLI_KSM=true …
```
> Let Error Message Return for Helm Upgrade Install

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
- test/manual/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/manual/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/manual/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
Handles whitespace in the application name by writing the application name and restart value to separate lines in the temporary file. 
Also includes a change for the application name regex to detect for any value of `newrelic.appname` and not just "PHP Application", which fixes the long-standing behavior in redhat.yml which did not allow for multiple changes of `newrelic.appname`
> PHP recipe application name

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/darwin.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/nginx/linux.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
- recipes/newrelic/infrastructure/windows.yml
This PR does the following:
- Enables the `infrastructure-agent-installer` to send new `INFRA_KEY` metadata after it is successfully installed on a host. The `newrelic-cli` receives this data and makes it available to the rest of the recipes to be installed after the `infrastructure-agent`.
- Updates the `validationNrql` to contain a `WHERE` clause that relies on the `INFRA_KEY`, for example:
```WHERE reportingAgent = '{{.INFRA_KEY}}'```
Changes has been so far scoped to: infra agents (except Windows), MySQL and NGINX for RHEL, pending on additional tests and team feedback.
Related: https://github.com/newrelic/newrelic-cli/pull/1440
> feat(ohi): infrastructure agent key validation

- recipes/newrelic/infrastructure/kubernetes.yml
Customers recently got the following errors after March 24th.
```
execution failed for kubernetes-open-source-integration: exit status 1: The CustomResourceDefinition "clusterserviceversions.operators.coreos.com" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```
We think the issue is same as [this issue](https://github.com/operator-framework/operator-lifecycle-manager/issues/2767) and follow[ the fix ](https://github.com/operator-framework/operator-lifecycle-manager/pull/2771)to make this PR. 
Test 2>&1 >/dev/null only keeping stderr in ERROR
```
xqi@TFXCKKXMP9 Chapter09 % ERROR=$(k create -f gs-ping-deployment.yaml 2>&1 >/dev/null)
xqi@TFXCKKXMP9 Chapter09 % echo $ERROR                                                 
xqi@TFXCKKXMP9 Chapter09 % ERROR=$(k …
```
> Fix The CustomResourceDefinition Installation Error

- recipes/newrelic/infrastructure/ohi/apache/debian.yml
- recipes/newrelic/infrastructure/ohi/apache/rhel.yml
- recipes/newrelic/infrastructure/ohi/cassandra/debian.yml
- recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
- recipes/newrelic/infrastructure/ohi/consul/debian.yml
- recipes/newrelic/infrastructure/ohi/consul/rhel.yml
- recipes/newrelic/infrastructure/ohi/couchbase/debian.yml
- recipes/newrelic/infrastructure/ohi/couchbase/rhel.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/debian.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/rhel.yml
- recipes/newrelic/infrastructure/ohi/elasticsearch/suse.yml
- recipes/newrelic/infrastructure/ohi/haproxy/debian.yml
- recipes/newrelic/infrastructure/ohi/haproxy/rhel.yml
- recipes/newrelic/infrastructure/ohi/memcached/debian.yml
- recipes/newrelic/infrastructure/ohi/memcached/rhel.yml
- recipes/newrelic/infrastructure/ohi/mongodb/debian.yml
- recipes/newrelic/infrastructure/ohi/mongodb/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
- recipes/newrelic/infrastructure/ohi/nagios/debian.yml
- recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
- recipes/newrelic/infrastructure/ohi/nginx/suse.yml
- recipes/newrelic/infrastructure/ohi/postgres/debian.yml
- recipes/newrelic/infrastructure/ohi/postgres/rhel.yml
- recipes/newrelic/infrastructure/ohi/rabbitmq/debian.yml
- recipes/newrelic/infrastructure/ohi/rabbitmq/rhel.yml
- recipes/newrelic/infrastructure/ohi/redis/debian.yml
- recipes/newrelic/infrastructure/ohi/redis/rhel.yml
- recipes/newrelic/infrastructure/ohi/varnish/debian.yml
- recipes/newrelic/infrastructure/ohi/varnish/rhel.yml
This PR enables all Linux OHIs to complete their NRQL validation via the Infrastructure Agent's Entity Key which is consumed by the `newrelic-cli` from this agent and made available subsequently for the rest of OHIs to be installed on a host.
> feat(ohi): infrastructure entity key validation

- recipes/newrelic/infrastructure/kubernetes.yml
Recently, I find 2>&1 >/dev/null can be used to simplify the existing helm error handling logic
So I make the corresponding changes to use 2>&1 >/dev/null in handling helm related errors
The following proved that With 2>&1 >/dev/null, ERROR only keeps the error message if `$?` is non-zero and is empty if `$?` is zero
```
xqi@TFXCKKXMP9 Downloads % helm repo add newrelic https://helm-charts.newrelic.com                 
"newrelic" already exists with the same configuration, skipping
xqi@TFXCKKXMP9 Downloads % echo $?                                                                 
0
xqi@TFXCKKXMP9 Downloads % helm repo add newrelic https://helm-charts.newrelic.com 2>&1 >/dev/null 
xqi@TFXCKKXMP9 Downloads % helm repo add newrelic https://helm-charts.newrelic.comm 2>&1 >/dev/null
Error: …
```
> Simplify Helm ERROR Handling Logic

- recipes/newrelic/infrastructure/ohi/nginx/linux.yml
Using metadata functionality to capture `stub_location` and `stub_status_url` values that could be triggering exit status 3
> fix: adding metadata output to collect nginx information

- recipes/newrelic/infrastructure/debian.yml
This PR
- Resolves [NR-60710](https://issues.newrelic.com/browse/NR-60710) 
- Added logs for the installation failures of the debian infra agent. 
- Attempting to resolve the error "Sub-process /usr/bin/dpkg returned an error code (1)" by reconfiguring, installing and fixing the missing, unpacked and broken dependencies.
> fix(debian): reconfig dpkg if broken dependencies

- recipes/newrelic/infrastructure/ohi/apache/debian.yml
- recipes/newrelic/infrastructure/ohi/apache/rhel.yml
Adds a backwards-compatible alias `NEW_RELIC_APACHE_STATUS_URL` for `NR_CLI_STATUS_URL`
> chore(apache): Alias env vars

- recipes/newrelic/infrastructure/logs/linux-logs.yml
- test/definitions/infra-agent/suse154-infra.json
- test/definitions/logging/suse154-logs.json
- Adds logs support for SUSE platform versions 15-SP[1-4]
- Checks `platformFamily` field for `suse` as it's consistently populated for SUSE unlike `platform`
- Adds nonregression tests for 15-SP4 infra/logs
> SUSE 15-SPx logs support

- recipes/newrelic/infrastructure/logs/linux-logs.yml
- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/redis/debian.yml
- test/definitions/ohi/linux/mysql-ubuntu22.json
- test/definitions/ohi/linux/redis-ubuntu22.json
Adding support for recipes with pinned Ubuntu versions (mysql & redis) to match the infra agent [docs](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/get-started/requirements-infrastructure-agent/#operating-systems)
> chore(ohi): Update pinned Ubuntu versions

- .github/workflows/nonregression-eu.yml
Re-instate `max-parallel` for GHA's Non-regression EU tests.
> Re-instate max-parallel for EU tests

- recipes/newrelic/apm/php/debian.yml
- recipes/newrelic/apm/php/redhat.yml
This PR adds clear, helpful error messages for the following error scenarios.
Recipe Checklist
1. When PHP is not installed
2. When php-fpm and Apache are not installed or running
3. When Apache is running, but the PHP module is not enabled
> feat(php): add helpful error messaging for some important preInstall checks

- recipes/newrelic/infrastructure/kubernetes.yml
Update k8s minimum version to 1.23.
Added a check for `KUBECTL_VERSION=$($SUDO $KUBECTL version --short 2>&1)` command to see if it return's an error containing `unknown flag: --short` which means the user has kubectl v1.28 and rerun the command without using `--short` flag.
I tested this recipe locally on kubectl version 1.23 and 1.28 and the installation worked without errors.
> feat: Update minimum k8s version

- recipes/newrelic/infrastructure/kubernetes.yml
This PR updates kube-state-metrics version to 2.10.0
> feat: Update ksm version in kubernetes recipe

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Follow-up task for the super agent recipe now that the fleet management endpoint is ready.
scope:
the default install should define the required configs so that the agents are registered in Fleet.
at the moment, this needs:
define the opamp url depending on the NEW_RELIC_REGION parameter (US, EU, STAGING):
[opamp.staging-service.newrelic.com/v1/opamp](http://opamp.staging-service.newrelic.com/v1/opamp)
[opamp.service.newrelic.com/v1/opamp](http://opamp.service.newrelic.com/v1/opamp)
[opamp.service.eu.newrelic.com/v1/opamp](http://opamp.service.eu.newrelic.com/v1/opamp)
define the api-key using the ingest_key (same used for the infra-agent and otel collector)
add a new param to enable customers to optionally disable the opamp connection, proposal:
NR_CLI_FLEET_ENABLED=false (default value …
> Enable Fleet connection (opamp) by default (NR-165936)

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/logs/linux-logs.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Move filelog removal to the main super-agent recipe to not send any logs if NRI_HOST_MONITORING is 'newrelic'.
> Super-agent install recipe, do not send any logs if NRI_HOST_MONITORING is 'newrelic'(NR-179505)

- recipes/newrelic/infrastructure/ohi/cassandra/debian.yml
- recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
- test/deploy/linux/cassandra/install/debian/roles/configure/tasks/main.yml
- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/installCassandra.yml
- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/installDependencies.yml
- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/main.yml
- test/deploy/linux/cassandra/install/rhel/roles/configure/tasks/main.yml
- test/deploy/linux/cassandra/install/rhel/roles/prepare/tasks/installCassandra.yml
- test/deploy/linux/cassandra/install/rhel/roles/prepare/tasks/installDependencies.yml
- test/deploy/linux/cassandra/install/rhel/roles/prepare/tasks/installJava.yml
- test/deploy/linux/cassandra/install/rhel/roles/prepare/tasks/main.yml
- test/manual/definitions/ohi/linux/apache-cassandra-debian10.json
- test/manual/definitions/ohi/linux/apache-cassandra-linux2.json
**Deployer scripts**
* Enable JMX authentication and add user with credentials. **NOTE**: Try as I might, I could not figure out how to escape the `!` that is usually included in our standard test credentials.
```
user: newrelic
pw: Virtuoso4all
```
* AL2 quirks
* When installing cassandra with `yum`, configuration files are located at `/etc/cassandra/conf/`, instead of the default `/etc/cassandra`
**Testing**
**NOTES**: 
* The current `rhel` recipe is broken. You will need to reference the fixed recipe in this branch when testing.
* To fully validate that the CLI install was successful, ensure that you see a new cassandra entity show up in the entity explorer.
1. If you run demo-deployer in a docker container with open-install-library as a mounted volume, you can reference local deploy …
> chore: Fix cassandra deploy scripts

- docs/recipe-spec/recipe-spec.md
- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
Allows `super-agent` as an`infrastructure-agent` alternative/substitute dependency for OHIs. Related to: https://github.com/newrelic/newrelic-cli/pull/1534 in the CLI side.
Ref: [NR-173011](https://new-relic.atlassian.net/browse/NR-173011)
> feat(ohi): add super-agent as infra-agent substitute dependency for OHIs

- recipes/newrelic/infrastructure/kubernetes.yml
Updating the script to check if user is installing in a GKE Autopilot. If they are, it will turn off privileged mode, control plane and then turn off pixie since it requires privileged access. It also turns off logging which is not currently supported in GKE autopilot.
> feat(kubernetes): Add gke autopilot check to script

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
- recipes/newrelic/infrastructure/ohi/mysql/rhel.yml
- recipes/newrelic/infrastructure/ohi/mysql/suse.yml
Fixes the MySQL recipes for MySQL 5.6 for Debian, RHEL and Suse.
Creates a faux user without permissions so that the DROP USER command never fails, regardless of whether the user has been created or not. This allows the recipe to succeed in creating a user for the MySQL integration.
This method also works on newer versions of MySQL and MariaDB, ensuring forward compatibility.
> fix: Mysql 5.6 create user

- recipes/newrelic/infrastructure/ohi/nginx/linux.yml
- recipes/newrelic/infrastructure/ohi/nginx/suse.yml
Enables log ingestion of `Nginx`'s currently active `access/error` logs only, excluding any rotated ones (access.log.1, etc). Ref: [NR-216304](https://new-relic.atlassian.net/browse/NR-216304).
> fix(ohi): Ingest current nginx log only

- recipes/newrelic/infrastructure/ohi/cassandra/debian.yml
- recipes/newrelic/infrastructure/ohi/cassandra/rhel.yml
- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/installCassandra.yml
Enables log ingestion of `Cassandra`'s currently active `system/debug` logs only, excluding any rotated ones (system.log.1, etc). Ref: [NR-216306](https://new-relic.atlassian.net/browse/NR-216306).
> fix(ohi): Ingest current cassandra logs only

- test/deploy/linux/mysql/install/rhel/roles/configure/tasks/main.yml
Fixes `Header V4 RSA/SHA256 Signature, key ID a8d3785c: NOKEY` error that is causing the `mysql-rhel.json` test to fail. Ref: [NR-218868](https://new-relic.atlassian.net/browse/NR-218868).
> fix(ohi): Update gpg key url

- recipes/newrelic/infrastructure/kubernetes.yml
This change depends on https://github.com/newrelic/helm-charts/pull/1259
It adds support for enable logs integration in GKE autopilot by using no database or FileStore to persist fluent-bit database files
As FileStore will have an extra cost we want to enable users to select if they want to use that, or go without database (that will imply some logs being lost on fluent bit restarts)
> Add logging support for GKE autopilot

- test/deploy/linux/apache/deploy-application/dotNet/debian/roles/onbeforestart/tasks/main.yml
JIRA: https://new-relic.atlassian.net/browse/NR-218247
As part of this ticket I'm modifying the existing dotnet sample application installation ports to avoid the port address already in use issue during instrumentation
> chore(dotnet): Modifying ports to avoid port address issue

- recipes/newrelic/infrastructure/kubernetes.yml
depends on: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/1257 
removes the question asking if cluster is GKE Autopilot and instead reads the answer from the CLI variable `NR_CLI_GKE_AUTOPILOT` as created in the referenced PR: https://source.datanerd.us/nr1-dev-experience/marketplace/pull/1257
> update GKE autopilot question 

- recipes/newrelic/infrastructure/darwin.yml
Fixes an issue on macOS (darwin) which caused the Infrastructure Agent restart step to hang indefinitely.
> fix: MacOS restart agent hanging

- test/deploy/linux/java/docker-flow/roles/configure/tasks/main.yml
- test/manual/definitions/apm/java/linux/docker-flows/java-docker-flows.json
This PR will create a deploy config to instrument Java (Docker flow). This config consists of prerequisites to instrument Java such as install docker, install jdk, create a sample java application.
Ticket: [https://new-relic.atlassian.net/browse/NR-191190](https://new-relic.atlassian.net/browse/NR-191190)
> feat: Add deploy config for Java docker flow

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
This PR adapts the Super Agent recipe to the new `nr-otel-collector` Agent Type 0.1.0
Tests are failing because the Agent Type version 0.1.0 is not released yet. This should not be merged until we release the new Super Agent version.
> super_agent: nr-otel-collector agent type 0.1.0

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Use config examples to set up the super-agent, allowing to have empty agents.
Related to this modification in the super-agent [#484](https://github.com/newrelic/newrelic-super-agent/pull/484)
> Use config examples to set up the super-agent, allowing to have empty agents.

- recipes/newrelic/infrastructure/super-agent/rhel.yml
This PR fixes the installation in Amazon Linux where the URLs for the repo are not built in the same way as in RH.
> fix(superagent): fix repo installation in Amazon Linux

- recipes/newrelic/infrastructure/darwin.yml
This PR will define tags (custom attributes) when installing the infra-agent on macOS.
Ticket: [NR-266800](https://new-relic.atlassian.net/browse/NR-266800)
[NR-266800]: https://new-relic.atlassian.net/browse/NR-266800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tags): Define custom attributes for macOS

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
This PR:
- Adds the `fleet_id` configuration to the super-agent recipe
- Align some differences between scripts for different OS. Sadly unifying thes task is not currently supported by newrelic-cli
> feat(superagent): Add fleet

- recipes/newrelic/infrastructure/darwin.yml
It was recently noticed (via the team's monitoring infrastructure, since the last week) that customers trying to install the infrastructure agent on `darwin` (macOS) platforms seem to be encountering failures looking like the following: `performing GET request to http://localhost:18003/v1/status/entity`. 
Upon further investigation, it was found that most cases of these installation failures did not seem to happen upon the first instance of installation of the infra agent by customers; this error would occur 
- either when the customer would install the infra agent on a subsequent attempt (after a signup, followed by instrumentation of their infrastructure for the first time), 
- or, when they would use older versions of the CLI not pointing to the 0.67.1+ of open-install-library in which …
> chore: revert PR #1074 `feat(tags): Define custom attributes for macOS`

- test/deploy/linux/kubernetes/minikube/roles/prepare/tasks/main.yml
Updates the Kubernetes version used by minikube to fix failing tests due to unsupported version.
> fix: Update kubernetes v1.26.1

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/logs/linux-logs.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Rename environment variables pertaining to the Super Agent. Both the recipe(s) and the Super Agent itself will utilize the newly named environment variables.
> fix: Rename super agent env vars

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
- validator/schema-v1.json
Adds support for the following platforms:
- Amazon Linux
- CentOS version 7 or higher
- Debian version 10 or higher
- Red Hat Enterprise Linux (RHEL) 7 or higher
- Oracle Linux version 7 or higher
- SUSE Linux Enterprise Server (SLES) version 12, 15
- Ubuntu 16.04 LTS or higher
Whitespace removed from end of lines.
> fix: Super agent target modifications

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
This script creates the key pair and push the public one to New Relic. Also configures the super agent to use the key generated.
It fails to register the host saying that there is an error on the back end:
```
Error creating an identity: Validation error (FieldUndefined@[mutation]) : Field 'mutation' in type 'Query' is undefined
```
But we are supposing that the backend will behave correctly EOD
> Change super agent recipe to support System Identity registration (NR-273901)

- recipes/newrelic/infrastructure/windows.yml
Infra Agent config file on Windows has ANSI Encoding by default. This PR makes it UTF8.
> infra agent: enforce utf8 encoding on Windows config

- recipes/newrelic/infrastructure/super-agent/rhel.yml
This PR updates the super-agent's recipe to install fluent-bit manually on Amazon linux. This is needed because the [recommends package dependency](https://github.com/newrelic/newrelic-super-agent/blob/1abc91ceec135a3e26055ba406e90cdab3f1644a/.goreleaser.yml#L174) used in the super-agent's RPM (which usually installs fluent-bit as a dependency) isn't supported in the default RPM version in the AL2 x86 base image.
> [NR-295076] super-agent: manually install fluent-bit for amazon linux

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
IAM doesn't have system-identity-oauth in EU. There are no instances of system identity oauth running in EU. 
This change can be permanent.
> Use US OAuth urls instead of EU

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
This should be merged right after (And not before!) the next SuperAgent release that will remove -0.1.0. 
Otherwise the recipe will stop working since it will not know where to find that file.
> [SuperAgent] remove agentType version

- recipes/newrelic/infrastructure/ohi/mysql/debian.yml
add ubuntu version 24.4 support for mysql integration
[JIRA-NR-329834](https://new-relic.atlassian.net/browse/NR-329834)
Validation results:
Before adding 24.4 Ubuntu version support
output
After adding 24.4 Ubuntu version support
output
After adding support in OIL able to install mysql-integration
> fix(mysql): add ubuntu version 24.4 support for mysql integration

- recipes/newrelic/apm/php/debian.yml
Recently, php agent team have release few [agent changes](https://github.com/newrelic/newrelic-php-agent/pull/971) which broke php guided install. So, inorder to accommodate new agent changes, made required changes in the php recipe and validated.
Results:
1: Installation result of php recipe with this PR changes on top of failing installation host.
2: PHP installation Totally on new host
> fix(php): fixed php debian recipe to accommodate recent php agent changes

- test/definitions-eu/apm/dotNet/linux/debian10-nginx-aspnetcore.json
- test/definitions-eu/apm/dotNet/linux/ubuntu20-apache-aspnetcore.json
- test/definitions-eu/apm/dotNet/windows/iis-blank.json
- test/definitions-eu/apm/dotNet/windows/windows2016-iis.json
- test/definitions-eu/apm/dotNet/windows/windows2019-core-only-iis.json
- test/definitions-eu/apm/dotNet/windows/windows2019-iis.json
- test/definitions-eu/apm/java/deb10-supd-javatron.json
- test/definitions-eu/apm/java/deb10-sysd-custom-sh.json
- test/definitions-eu/apm/java/deb10-sysd-tomcat-cmd.json
- test/definitions-eu/apm/java/deb10-sysd-tomcat-sh.json
- test/definitions-eu/apm/java/deb11-apt-sysd-tomcat.json
- test/definitions-eu/apm/java/deb11-sysd-jboss.json
- test/definitions-eu/apm/java/rhl2-supd-javatron.json
- test/definitions-eu/apm/java/rhl2-sysd-custom-sh.json
- test/definitions-eu/apm/java/rhl2-sysd-tomcat-cmd.json
- test/definitions-eu/apm/java/rhl2-sysd-tomcat-sh.json
- test/definitions-eu/apm/java/rhl2-yum-docker-jboss.json
- test/definitions-eu/apm/java/rhl2-yum-sysd-tomcat.json
- test/definitions-eu/apm/java/ub20-apt-docker-jboss.json
- test/definitions-eu/apm/java/ub20-apt-docker-tomcat.json
- test/definitions-eu/apm/java/ub20-apt-sysd-tomcat.json
- test/definitions-eu/apm/php-agent/php-apache-fpm-wordpress-linux2.json
- test/definitions-eu/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/definitions-eu/apm/php-agent/php-apache-wordpress-linux2.json
- test/definitions-eu/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/definitions-eu/apm/php-agent/php-nginx-fpm-wordpress-linux2.json
- test/definitions-eu/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
- test/definitions/apm/us-php-apache-fpm-wordpress-ubuntu18.json
- test/definitions/apm/us-php-nginx-fpm-wordpress-linux2.json
**Issue:-** Currently in few of the demo deployer scripts, the validation output strings not correct, tests are showing as passed even though they are failing, due to validation output check string is not correctly entered.
[Jira Ticket](https://new-relic.atlassian.net/browse/NR-338891)
Updated the validate_output fields in the deployer scripts to use the correct regular expressions for specific agent installations.
Changes done in the variety of deployer scripts for the different agents, for example in PHP deployer scripts.
**PHP Deployer Script:**
From: "New Relic installation complete"
To: "PHP Agent\s+\(installed\)"
**Context**
The previous validate_output string, "New Relic installation complete", was too generic and indicated success for any installation. This update ensures that …
> fix(demo_deployer): Updated specific regex in validate_output's param

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Create L2 identities using L1 identity token in Agent Control installation.
> feat(agent-control): L2 identity creation

- recipes/newrelic/infrastructure/super-agent/debian.yml
- recipes/newrelic/infrastructure/super-agent/rhel.yml
- recipes/newrelic/infrastructure/super-agent/suse.yml
Remove references from Agent types.
⚠️  It needs released changes on the SA. I'll notify whenever is ready
> chore!: remove agent type references (NR-337618)

- recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml
`nri-mssql` install fails to download on restricted hosts where unencrypted traffic is not allowed.
> fix: use https for mssql integration download

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
Added:
- Max time 60
- Connect timeout
for identity curls calls in recipes of suse, rhel and debian.
And after modify the script into the helm for k8s to fix jq parse errores this changes are applied here too
> NR-361437-fix-jd-parse-error

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
Add $ERROR_MESSAGE after HTTP CODE logs during L2 and legacy identity request
>  fix/error concatenation message

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
This PR updates the endpoints to create L2 system identities for AC (same change as https://github.com/newrelic/helm-charts/pull/1587)
> chore: update ac system-identity creation endpoints

- recipes/newrelic/infrastructure/windows.yml
Issue:- Mentioned in the below jira ticket.
[Jira Ticket](https://new-relic.atlassian.net/browse/NR-374495)
Fix:- Escape square brackets in registry key paths in Windows installer recipe.
> fix(script): Escape square brackets in registry key paths

- recipes/newrelic/infrastructure/kubernetes.yml
- test/deploy/linux/kubernetes/minikube/roles/prepare/tasks/main.yml
Add Kube 1.32 support and drop 1.27
Update testing to use Kube v1.32.0 instead of v1.31.0 for minikube
Test Plan: Spun up a v1.32 cluster on minikube and installed NRI Bundle with a local copy of the `kubernetes.yml` from this PR.
> feat(kubernetes): Add Kube 1.32 support and drop 1.27

- test/definitions/ohi/linux/consul-debian.json
- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/installDependencies.yml
- test/deploy/linux/consul/install/debian/roles/configure/tasks/main.yml
This PR aims to resolve consul-debian and cassandra-debian failures
- The method of adding a repository GPG key using apt-key is deprecated. To solve this issue, we have added the GPG key directly to the trusted keyrings directory.
- Added signed-by to reference the GPG key, ensuring APT trusts the repository using the specified GPG key.
- Configured `openjdk-11-jdk` separately before installing cassandra.
> fix(debian-tests): Resolve consul-debian and cassandra-debian failures

- recipes/newrelic/infrastructure/windows.yml
Issue mentioned in the [Jira Ticket](https://new-relic.atlassian.net/browse/NR-400198)
**Resolution done:-**
I updated the script code that removes the old logic that manually escaped square brackets ([, ]) in registry keys using -replace. This was unnecessary because PowerShell's -LiteralPath parameter can handle special characters in paths without requiring manual escaping. The old logic was error-prone and introduced parsing issues, such as "Missing type name after '['." By replacing it with -LiteralPath, the updated code simplifies the implementation, avoids these errors, and ensures compatibility with registry keys containing special characters. This change improves both the reliability and maintainability of the function.
I tested my changes after creating few test registery keys …
> fix(script): Fixed error with Infra Guided Install on windows hosts

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
This PR enforces installing only one HOST instrumentation agent in the Agent Control installation. Infra Agent or Opentelemetry Collector, but not both.
> feat(ac): install only one agent (infra|otel)

- recipes/newrelic/infrastructure/ohi/varnish/debian.yml
- recipes/newrelic/infrastructure/ohi/varnish/rhel.yml
**Issue :-** The INSTANCE_NAME variable in the Varnish Cache integration recipe was not correctly defaulting to new_relic when the user did not explicitly define it. This resulted in the following error during installation:
**Error:-**
> `DEBUG validation error encountered: exit status 1: [ERR] Error input validation failure: instance_name must not be blank
> `
[Jira Ticket](https://new-relic.atlassian.net/browse/NR-386250)
**Resolution:** 
- The issue has been resolved by explicitly handling the default value for INSTANCE_NAME in the recipe. The updated recipe ensures that the variable is never blank and defaults to new_relic when not provided.
- After fixing the recipe, varnish-cache-open-source-integration is installing successfully when user don’t define the value for instance_name. …
> fix(varnish): Added default values for instance_name and params config file

- recipes/newrelic/infrastructure/ohi/nagios/debian.yml
- recipes/newrelic/infrastructure/ohi/nagios/rhel.yml
- test/manual/readme.MD
JIRA - https://new-relic.atlassian.net/browse/NR-380307
This PR automates the installation of Nagios plugins if they are not present on the user's host. We have noticed numerous installation failures due to missing plugins, even though this requirement is mentioned as a prerequisite in the installation UI.
- RHEL tests when plugins are not found.
- RHEL tests when plugins are already installed.
- Debian tests when plugins are not found.
- Debian tests when plugins are already installed.
> fix: Update recipe to automate nagios plugin install

- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/ubuntu.yml
This PR addresses the issue of infra agent warnings during the guided install process. The warnings indicate that the GPG key is stored in the legacy trusted.gpg keyring, which is deprecated. The changes ensure that the GPG key is added to the /etc/apt/trusted.gpg.d/ directory and remove any existing keys from the legacy keyring.
Changes Made
Update add_gpg_key Task:
Remove the key from the legacy keyring if it exists, suppressing any error messages.
Add the key to the /etc/apt/trusted.gpg.d/ directory using gpg --dearmor.
Validation:
Please find details in [this](https://new-relic.atlassian.net/browse/NR-377335)
> Fix: Address infra agent warnings related to legacy trusted.gpg keyring

- recipes/newrelic/infrastructure/awslinux.yml
- recipes/newrelic/infrastructure/centos_rhel.yml
- recipes/newrelic/infrastructure/debian.yml
- recipes/newrelic/infrastructure/suse.yml
- recipes/newrelic/infrastructure/ubuntu.yml
**Context:**  
We now publish FIPS-compatible packages for the New Relic Infrastructure Agent on Linux. Customers can install these packages via their package manager using the new package name `newrelic-infra-fips` (instead of `newrelic-infra`).
**Scope:**  
This update introduces support for a new environment variable `NEW_RELIC_FIPS_ENABLED` in the Linux installation recipes.
**Changes:**  
- Added support for the `NEW_RELIC_FIPS_ENABLED` flag in the following recipes:
- `ubuntu.yml`
- `suse.yml`
- `debian.yml`
- `awslinux.yml`
- `centos.yml`
- **Default Behavior:** If the flag is not set or set to `false`, the recipes will install the default `newrelic-infra` package (no changes to existing flows).
- **FIPS Mode:** If the flag is set to `true`, the recipes will install the …
> fix:[install-recipe] Add option to install FIPS package

- recipes/newrelic/infrastructure/awslinux.yml
GSTE: https://new-relic.atlassian.net/browse/NR-404232
- This PR addresses a bug in the New Relic Infrastructure agent installation process for Linux. The current command (yum -y -q install newrelic-infra) fails to upgrade the agent on AWS linux hosts where an older version is already installed. Instead, it only installs the agent when it's not present. To ensure correct behavior, the installation process has been modified. The revised command now checks for the agent's presence and either upgrades it or installs the latest version appropriately:
`yum list installed newrelic-infra >/dev/null 2>&1 && yum update newrelic-infra -y -q || yum install newrelic-infra -y -q`
This fix will ensure the agent is either upgraded or installed consistently.
> fix(linux): Updated infra install command to include upgrade as well

- test/deploy/linux/cassandra/install/debian/roles/prepare/tasks/installCassandra.yml
Context:
Cassandra test was failing because the apt package was not able to find the gpg key as it was being added using `apt-key add` method which is an old method of gpg key addition, which has been deprecated in Cassandra. 
Fix:
Updated the gpg key addition method and correct Cassandra repository path. Followed the steps provided in Cassandra [official doc](https://cassandra.apache.org/doc/latest/getting_started/installing.html#debian) for installing Cassandra and updated the ansible script according to that.
Local test success validation:
> fix(Cassandra-test): fix failing Cassandra gpg key error.

- test/definitions-eu/agent-control/logs/redhat8-agent-control-logs-eu.json
- test/definitions-eu/infra-agent/rhel/redhat8x-infra.json
- test/definitions/agent-control/logs/redhat8-agent-control-logs.json
- test/definitions/logging/redhat8-logs.json
- test/definitions/smoke/redhat84-infra.json
- test/manual/definitions/infra-agent/redhat8-infra.json
- Updated the deprecated RHEL8 AMI images to new ones.
Before changes Error:
> fix(RHEL8): Updated deprecated AMI images with new ones

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
Adapt AC status response check to the new format.
Cannot be merged until the next release of the AC has been done.
> chore(ac): update AC HTTP server payload parse

- recipes/newrelic/infrastructure/agent-control/debian.yml
- recipes/newrelic/infrastructure/agent-control/rhel.yml
- recipes/newrelic/infrastructure/agent-control/suse.yml
Revert change made to check AC health.
Payload:
```yaml
{
"agent_control": {
"healthy": true
},
"fleet": {
"enabled": true,
"endpoint": "https://opamp.service.newrelic.com/v1/opamp",
"reachable": true
},
"sub_agents": {
"nr-infra": {
"agent_id": "nr-infra",
"agent_type": "newrelic/com.newrelic.infrastructure:0.1.0",
"agent_start_time_unix_nano": 1745410137922303000,
"health_info": {
"healthy": true,
"status": "{\"healthy\":true}",
"start_time_unix_nano": 1745410137911429600,
"status_time_unix_nano": 1745410175247852800
}
}
}
}
```
> fix(ac): revert AC HTTP server health payload change

- recipes/newrelic/infrastructure/ohi/sql/ms-sql.yml
- Enable Query Level monitoring for `nri-mssql` integration
- Add install support for Azure SQL Managed Instance
- Removed `processMatch` as process is not present on the host in case of azure sql managed instance.
- When `NEW_RELIC_AZURE_DEPLOYMENT_TYPE` is set to `AZURE_SQL_MANAGED_INSTANCE`
- Install and configure agent +integration with Azure SQL Managed Instance config details
- When `NR_CLI_SLOW_QUERY` is set Query level Monitoring should be enabled for all non default databases of the Azure SQL Managed Instance.
- When `NR_CLI_SLOW_QUERY` is set enable Query level Monitoring for all instances and databases detected in local.
Install for Instrumenting Self Host/Azure SQL VM servers using nri-mssql integration.
Testing Details - 
Tested both normal installation and installation with …
> feat: add enabling QLM & Azure SQL Managed Instance support for ms-sql install recipe 

- test/definitions-eu/agent-control/debians/ubuntu18-agent-control-eu.json
- test/definitions-eu/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/definitions-eu/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/definitions-eu/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
- test/definitions-eu/infra-agent/debians/ubuntu18-infra.json
- test/definitions/agent-control/debians/ubuntu18-agent-control.json
- test/definitions/apm/us-php-apache-fpm-wordpress-ubuntu18.json
- test/definitions/ohi/linux/nginx-ubuntu.json
- test/manual/definitions/apm/php-agent/php-apache-fpm-wordpress-ubuntu18.json
- test/manual/definitions/apm/php-agent/php-apache-wordpress-ubuntu18.json
- test/manual/definitions/apm/php-agent/php-nginx-fpm-wordpress-ubuntu18.json
- test/manual/definitions/infra-agent/ubuntu18-infra.json
- test/manual/definitions/ohi-auto-config/linux/apache-mysql-ubuntu18-auto.json
- test/manual/definitions/ohi/linux/apache-mysql-ubuntu18.json
- Replaced deprecated ubuntu18.04 AMI images with alternative ones
> fix: Replaced deprecated ubuntu18.04 AMI images with alt ones

- recipes/newrelic/apm/dotNet/linux-systemd.yml
This PR updates the .NET agent Linux install recipe to use a new public signing key and also replace the use of `apt-key add` (which is deprecated) with the current best practice of saving the key to a specific file and configuring the APT repo definition to be signed by that file.
Note: this is in draft status until the .NET agent does it's next release, which we plan to do early this week.
> fix: Update APT repo configuration steps in dotnet linux recipe

- .github/workflows/nonregression-eu.yml
- .github/workflows/nonregression.yml
The regression test in OIL is using deployer to provision the host and perform service installation and instrumentations to test for the New relic integrations.
For security concerns Crowdstrike is required on every provisioned Ec2 instanc. Installation of crowdstrike is handled by the deployer image. 
As part of OIL we need to include the crowdstrike install role and pass the creds stored in GIT for the. deployer image to install crowdstrike on the provisioned host
Find more details on this [ticket](https://new-relic.atlassian.net/browse/NR-314081)
Tests can found in this [sub-task](https://new-relic.atlassian.net/browse/NR-436590)
Confluence page : https://newrelic.atlassian.net/wiki/spaces/VIRTUOSO/pages/edit-v2/4474799913?draftShareId=c5c4d459-0239-46f1-a3b4-4dabade973ea
> fix(crowdstrike-fix): Fix crowdstrike installation on the provisioned host.

- test/deploy/crowdstrike/roles/configure/tasks/main.yml
Currently onboarding-e2e-tests are failing during the provisioning of EC2 instances. The failure is due to an error during the CrowdStrike installation, which is likely caused by an expired hash. Given that we are in the process of deprecating CrowdStrike, this pull request (PR) is a temporary fix to bypass the installation and confirm a successful deployment. A subsequent PR will address all necessary changes to fully deprecate the CrowdStrike installation.
> fix: Skip CrowdStrike installation to unblock onboarding tests

- recipes/newrelic/ebpf/centos.yml
- recipes/newrelic/ebpf/ubuntu.yml
This PR has the following changes:
- 2 new env's are introduced in the config - `DOWNLOADED_PACKAGED_HEADERS_PATH` and `DISTRO_KERNEL_HEADERS_PATH`
- Updated description for `DROP_DATA_FOR_ENTITY` env.
- Add new task to install linux headers.
- Recreate config and TLS certs in case of a agent upgrade.
> fix(ebpf): Recreate eBPF config on agent upgrade
